### ISSUE TITLE
Add support for Instant java class

### ISSUE THREAD

**Issue by alxxyz** [neo4j/neo4j-java-driver#1059]
In `org.neo4j.driver.Value` class is already support for `LocalDateTime`, `OffsetTime`.
Please add support also for `java.time.Instant`.

**Comment by michael-simons** [comment]
Hey @alxxyz 

The values provide access to datatypes that can be stored natively inside Neo4j. `java.time.Instant` is an super type that doesn't have a direct pendant inside the database, we would have to guess what's being meant.

@injectives and I discussed this topic and came to the following conclusions:

While all the `LocalXXX` types allow you to don't care about the timezone ("You want to represent a point in time without worrying about time zones."), an `Instant` does not: It is "An instantaneous point on the time-line." and part of that timeline is a timezone.

The local date values have no means of knowing the reference time zone.

Therefor we will stick with the default mappings: https://neo4j.com/docs/java-manual/current/cypher-workflow/#java-driver-type-mapping (Table "Map Neo4j types to Java types")

You can always create a custom helper like this:

```java
static Value value(Instant instant) {
    return Values.value(instant.atOffset(ZoneOffset.UTC));
}

static Instant asInstant(Value value) {
	return value.asZonedDateTime().toInstant();
}
```

The latter being the code Spring Data Uses. Of course we're making assumptions there, but that is fine as it is on a higher level, and not down the transport layer.
