### ISSUE TITLE
[Feature Request] Make Config, SessionConfig and TransactionConfig implement Serializable

### ISSUE THREAD

**Issue by mattcasters** [neo4j/neo4j-java-driver#1081]
This is to make it easier to send these configurations across the network in a running Apache Beam pipeline.
The API of Beam asks for any metadata driving all transforms and functions to be Serializable.  Reading from and writing to Neo4j is no exception to this.  This requirement in turn forces us to mirror all methods of Config, SessionConfig and TransactionConfig in new Serializable classes and write new Builders for this as well.

**Comment by michael-simons** [comment]
This has been implemented with #1082 in ddb3959204da40d8f139dee261ec93a15b70338e.
