### ISSUE TITLE
Automatically figure out neo4j+s protocol

### ISSUE THREAD

**Issue by mattcasters** [neo4j/neo4j-java-driver#1121]
As a feature request it would be great to see the current automatic behavior with respect to encryption setting extend to the neo4j+s protocol used with Aura.  The same thing can be said for the self signed certificate protocol neo4j+ssc

I've been quite confused in the past about the 3 ways the Java driver can be configured: withEncryption(), withoutEncryption() and then the 3rd (but unfortunately not explicitly mentioned) state: automatic.  My point is that if we're automatically configuring encryption options, we might as well configure neo4j+s and neo4j+ssc automatically as well?  Just an idea.

**Comment by injectives** [comment]
Thanks for the request. 👍 

Would you mind elaborating a little bit for us please? We don't really get the idea.

Providing that the `Config` object has default encryption and `TrustStrategy`, the driver automatically enables encryption and certificate policy based on the scheme used. For instance, `neo4j+s` results in enabling encryption with system CA certificates.

**Comment by mattcasters** [comment]
It could just have been neo4j:// then. All these things make it needlessly complicated.  Just like the need to verify connectivity and so on. It's like you want the driver to be some elite, obscure thing, that only the smartest folks can use. Just keep it as simple as possible.

**Comment by AndyHeap-NeoTech** [comment]
Hi @mattcasters. I've added a card to the teams backlog to review the developer experience around this area and to see what potential changes could help. This will not be something that is worked on immediately as we have quite a few high priority items for Q1. We will close this issue at this time, and comment on it as and when we have further news or questions.
