### ISSUE TITLE
1.0.0-M02 cannot handle propery sizes over ~10Kb

### ISSUE THREAD

**Issue by kostmich** [neo4j/neo4j-java-driver#119]
I'm trying out Neo4j version 3.0.0-M02 using the neo4j-java-driver driver version 1.0.0-M02.
1. I'm creating a node with a property with ~10Kb of data.
2. When I retrieve the node the data has changed, but not the length.

If I create the node with smaller amount of data (~1Kb) it works as it should.

```
byte[] b = new byte[1000]; //works
byte[] b = new byte[7000]; //does not work
new Random().nextBytes(b);

sun.misc.BASE64Encoder encoder = new sun.misc.BASE64Encoder();
String data = encoder.encode(b);

Session session = GraphDatabase.driver("bolt://localhost").session();

String createQuery = "CREATE (a:Asset {" +
        "id : {id}," +
        "type : 'test'," +
        "created : {created}," +
        "data: {data}" +
        "}) RETURN a";

String id = UUID.randomUUID().toString();
long created = System.currentTimeMillis();

Map<String,Value> createValues = Values.parameters("id",id,"created",created,"data",data);

session.run(createQuery,createValues);

String matchQuery = "MATCH (a:Asset {id : {id}}) RETURN a.data as data";
Map<String,Value> matchValues = Values.parameters("id",id);

ResultCursor matchCursor = session.run(matchQuery,matchValues);

matchCursor.list().get(0).asMap().forEach((k,v) -> {
    Assert.assertEquals(data.length(),v.asString().length());
    Assert.assertEquals(data,v.asString());
});
session.close();
```

**Comment by kostmich** [comment]
The version I've tested is from maven:
`<dependency>
            <groupId>org.neo4j.driver</groupId>
            <artifactId>neo4j-java-driver</artifactId>
            <version>1.0.0-M02</version>
        </dependency>`

I cloned the repo, branch 1.0 and this version works as expected!

So, I guess you can close this...

**Comment by technige** [comment]
In that case this sounds like a server-driver mismatch due to incremental changes. Closing issue.
