### ISSUE TITLE
Regression: Concurrent deletion of a Node no longer results in a TransientException

### ISSUE THREAD

**Issue by GrahamLea** [neo4j/neo4j-java-driver#1231]
A `TransientException` is no longer thrown if a node is deleted while a query is trying to return it. This can result in higher-level libraries (OGM, in my case) attempting to interpret the result and incurring an error.

# Context
- Neo4j version: *Harness* 4.2.0+ (works with <= 4.1.9)
- Neo4j Mode: Single instance
- Driver version: Java language driver <= 4.4.5
- Operating system: MacOS

# Expected Behavior
Given: Concurrent requests for both deleting and retrieving the same node label
When: A query streaming nodes finds that one of the nodes in its list has been deleted
Then: A `TransientException` should be thrown (as was the case before Neo4j 4.2)

# Actual Behavior
No `TransientException` is thrown. Neo4j OGM attempts to hydrate objects from the result, fails, and throws a `MappingInstantiationException`.

# Reproduction
1. Clone `https://github.com/GrahamLea/neo4j-bugs`
2. Load in IntelliJ IDEA
3. In pom.xml, change neo4j.version to 4.2.0
4. Run `TestNodeTest.raises TransientExceptions during concurrent modifications`
5. It should fail (try running again or setting `NODE_COUNT` higher if not)
6. In pom.xml, change neo4j.version back to 4.1.9
7. Run test again and it will pass

# Comments
The query executes successfully, and OGM starts mapping the results. However, there is (incomplete?) data for the deleted node, which is mapped into a `NodeModel` instead of the proper `@NodeEntity` target class, as shown in the debug data below. 
![image](https://user-images.githubusercontent.com/754403/169756198-c2ef6fea-09d7-4c7d-aadf-633d3b71a86e.png)

This then results in a `ClassCastException`, which in is caught and re-thrown as a `MappingInstantiationException`.

I'm guessing it's possible this is a regression in Neo4j itself, rather than client-side libraries. But seeing as it's [`ErrorUtil`](https://github.com/neo4j/neo4j-java-driver/blob/d38816bdf6b220224312618acb44959ade25a3e6/driver/src/main/java/org/neo4j/driver/internal/util/ErrorUtil.java#L82) in this repo which should be throwing a `TransientException`, I thought this would be the best place to start.

**Comment by injectives** [comment]
Thank you for detailed overview of the problem.

`ErrorUtil` is used to create an appropriate exception object based on what driver gets from the server. It seems like this should be investigated by the server people.

**Comment by GrahamLea** [comment]
Sure, no problem. I can put a case in against the server.
Are you able to help me out by letting me know how I can get the driver to output what it's receiving from the server so that I can see how that's changed between versions?

**Comment by injectives** [comment]
I have mentioned this to our server people. It probably makes sense to open a server issue for tracking purposes.

You will get a lot more details, including messaging, if you enable logging when you create the driver. Just use the following config:
```
Config.builder()
           .withLogging( Logging.console( Level.FINE ) )
           .build();
```

**Comment by GrahamLea** [comment]
Raised against the server here: https://github.com/neo4j/neo4j/issues/12890
