### ISSUE TITLE
Fatal error occurred in the pipeline

### ISSUE THREAD

**Issue by destinccc** [neo4j/neo4j-java-driver#1287]
neo4j-java-driver 4.2.7
sometimes still throw this exception:Fatal error occurred in the pipeline, xxx Connection reset by peer;
myconfig is: 
Config config = Config.builder()
            .withMaxConnectionLifetime(30, TimeUnit.MINUTES)
            .withConnectionLivenessCheckTimeout(0, TimeUnit.SECONDS)
            .withMaxConnectionPoolSize(-1)
            .withConnectionAcquisitionTimeout(2, TimeUnit.MINUTES)
            .withTrustStrategy(Config.TrustStrategy.trustAllCertificates())
            .withoutEncryption()
            .build();
    return GraphDatabase.driver(uri, AuthTokens.basic(username, password), config);

Help me.

**Comment by injectives** [comment]
Hello.

Based on the description, it looks like connection gets aborted.

The following is suggested:
- investigating why it might happen in the specific environment
- using managed transactions API to benefit from automatic retries
  - [executeRead](https://neo4j.com/docs/api/java-driver/5.3/org.neo4j.driver/org/neo4j/driver/Session.html#executeRead(org.neo4j.driver.TransactionCallback))
  - [executeWrite](https://neo4j.com/docs/api/java-driver/5.3/org.neo4j.driver/org/neo4j/driver/Session.html#executeWrite(org.neo4j.driver.TransactionCallback))
  - or implementing retry behaviour on a higher level, in that case it might be preferable to use [RetryableException](https://neo4j.com/docs/api/java-driver/5.3/org.neo4j.driver/org/neo4j/driver/exceptions/RetryableException.html) as a guidance

We hope it helps.
