### ISSUE TITLE
Java driver & Netty

### ISSUE THREAD

**Issue by tianshishouhu** [neo4j/neo4j-java-driver#1360]
Current situation: When high-risk vulnerabilities occur in Netty, the neo4j-java-driver version needs to be upgraded.
Suggestion: If the Netty version can be upgraded independently, modify the pom file without upgrading the neo4j-java-driver version.

**Comment by fbiville** [comment]
Hello, build tools like Maven and Gradle already allow you to fetch the various Netty components at a different version without upgrading the Java driver.

For instance, with Maven, you can add this to your own POM:

```xml
  <dependencyManagement>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-bom</artifactId>
        <version>${the.netty.version.you.want}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
  </dependencyManagement>
```

Doing so, however, introduces a risk of breaking the compatibility between Netty and the Java driver.

**Comment by tianshishouhu** [comment]
This is useless because the final JAR file (neo4j-java-driver) is embedded with the netty code (the io.netty file exists in Maven of META-INF) and cannot be modified in this way.

**Comment by injectives** [comment]
> This is useless because the final JAR file (neo4j-java-driver) is embedded with the netty code (the io.netty file exists in Maven of META-INF) and cannot be modified in this way.

Would you be able to let us know which driver versions are you talking about please?
Beginning with version 4.4.0, there is a driver artifact that no longer embeds that code:
- 4.4 `neo4j-java-driver-slim` https://github.com/neo4j/neo4j-java-driver/releases/tag/4.4.0
- 5.0 `neo4j-java-driver` https://github.com/neo4j/neo4j-java-driver/releases/tag/5.0.0

**Comment by tianshishouhu** [comment]
neo4j-java-driver:4.4.11

**Comment by injectives** [comment]
> neo4j-java-driver:4.4.11

In that case using `neo4j-java-driver-slim` should let you manage the version.

**Comment by injectives** [comment]
> neo4j-java-driver:4.4.11

In that case it may be desirable to use the `neo4j-java-driver-slim` artifact that does not embed/shade the Netty.
