### ISSUE TITLE
Can we have examples of how to do a more complex create?

### ISSUE THREAD

**Issue by michelbetancourt** [neo4j/neo4j-java-driver#173]
e.g. using transactions, e.g. create 2 nodes that are related?

**Comment by zhenlineo** [comment]
Will the examples in [manual](http://neo4j.com/docs/developer-manual/3.0/index.html#driver-manual-index) solve your problem?

If not, please let us know what other examples you are interested. 

I will also add this manual link in readme to help others to find more example code.

**Comment by michelbetancourt** [comment]
Probably, but perhaps you can help address a gap in what I have learned so far.

I think what I find interesting is that with the embedded client you can do the following:
- Create - holding a reference to the created node
- Using that reference then create the second node and tie it to a relationship

With the Bolt driver we have the following creation patterns to deal with:
- Create the first node
- Then either:
- (a) Perform match then create of the node + relationship
- (b) Perform a merge then create of the node + relationship
- (c) Or combinations of (a) and (b) involving merge rather than create

Is an equivalent approach to using the embedded client for Bolt to perform the create/merge, e.g. using either the ID of the node or an index field?  And is there a difference in performance with the ID vs using an indexed field?  

Thoughts?
