### ISSUE TITLE
General SSLEngine problem

### ISSUE THREAD

**Issue by vlastik01** [neo4j/neo4j-java-driver#174]
I am running a Java Neo4j driver and have this :

  Driver driver = GraphDatabase.driver("bolt://localhost", AuthTokens.basic( "neo4j", "password" ) ); 
  Session session = driver.session();
when executing the last line, it will throw an error:

"General SSLEngine problem"
It worked for Neo4j 3.0.0 but after upgrading to 3.0.1

**Comment by pontusmelke** [comment]
Hi,
I think you need to delete the file `~/neo/known_hosts` (or at least open it and delete the line that starts with `localhost:7687`). When you are using `trust-on-first-use` the driver will accept the first certificate it sees and store it in the known_hosts-file, if the driver sees any other certificates it will reject them. However when you upgrade the server it will generate a new certificate and it will no longer match the certificate in the known_hosts-file.

Regards,
Pontus

**Comment by vlastik01** [comment]
Hi Pontus,

Your suggestion solved the problem.

Thank you a lot!!!!

I have posted the question on StackOverFlow, may I post your answer there?
Or if you want, you can post it and get a credit ..

http://stackoverflow.com/questions/37240461/general-sslengine-error-in-neo4j

Regards,
    Vlastimil

**Comment by pontusmelke** [comment]
Please go ahead and post the answer!

**Comment by rbramley** [comment]
Hit this when using a clean Neo4j docker instance with port forwarding, so the host IP already had a certificate from the previous instance. 

Note that the file was ~/.neo4j/known_hosts
