### ISSUE TITLE
No explicit Transaction Timeout setting

### ISSUE THREAD

**Issue by vince-bickers** [neo4j/neo4j-java-driver#180]
There may be cases when an application request should be timed out by the client if it takes longer than a certain number of seconds. The Java driver has no means to specify a request/transaction timeout parameter, and it doesn't appear to honour the server property `dbms.transaction_timeout` either.

**Comment by technige** [comment]
Thanks Vince. We've already got this one in our backlog to get sorted out so we're on it! :-)

**Comment by zhenlineo** [comment]
With the new Neo4j 3.1, all transactions goes to the db will respect `dbms.transaction_timeout`.

**Comment by mangrish** [comment]
@zhenlineo: Is that meant to be [dbms.transaction.timeout](http://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_dbms.transaction.timeout) instead?

Would you mind pointing me to or implementing a section on what properties the driver obeys so we can propagate this to the OGM/SDN?

**Comment by zhenlineo** [comment]
@mangrish Yes, it is `dbms.transaction.timeout`.

We will also talk with the doc team regarding your documentation suggestion :D

**Comment by mangrish** [comment]
Thanks for that @zhenlineo!

**Comment by jjaderberg** [comment]
@mangrish My understanding is that the drivers don't obey any particular settings in any special way. Rather, all settings are obeyed because they are obeyed by Neo4j. In other words, you can't configure the driver by setting something in _neo4j.conf_.
There are of course some configuration settings for Neo4j that will have more impact on the drivers than others, the Bolt connector settings for example. Is that the type of setting you would like to see more information about?

**Comment by mangrish** [comment]
@jjaderberg I guess thinking about this from an application developer's perspective, I would like to know the settings that I can explicitly control that have an affect on the driver's behaviour; whether that is explicitly via java configuration in the driver (which afaik is there) or via database properties; or at least a paragraph and a link to those properties. What do you think?

**Comment by jjaderberg** [comment]
@mangrish I think it could be a good idea to have a short summary of "important Neo4j settings" in the driver docs. I've added it to the backlog to investigate which settings might be interesting to call attention to, and if there are a reasonable number we can add a section to the driver chapter in the developer manual with links to the more detailed configuration documentation in the operations manual. Thanks for the suggestion! And if you have any settings in mind from working with OGM (beyond the transaction timeout one) let me know.
