### ISSUE TITLE
byte[] types are not support by Bolt driver, but are supported by Neo4j native API

### ISSUE THREAD

**Issue by graemerocher** [neo4j/neo4j-java-driver#182]
It seems that values of type `byte` are supported:

https://github.com/neo4j/neo4j-java-driver/blob/1.1/driver/src/main/java/org/neo4j/driver/v1/Values.java#L77

However, byte[] is not:

https://github.com/neo4j/neo4j-java-driver/blob/1.1/driver/src/main/java/org/neo4j/driver/v1/Values.java#L87

This is contrary to using the native `GraphDatabaseService` and the general statement that arrays of native of types are supported.

**Comment by pontusmelke** [comment]
Hi @graemerocher 
We are aware of this problem and it is on the road map to fix this in the drivers.

Thanks for reaching out!
Regards,
Pontus

**Comment by technige** [comment]
Closing driver issue. Please follow server issue https://github.com/neo4j/neo4j/issues/7640 instead.
