### ISSUE TITLE
The link to manual documentation in the README is broken / hard to find API docs

### ISSUE THREAD

**Issue by graemerocher** [neo4j/neo4j-java-driver#183]
Currently the README link to the manual is broken, and the only javadocs I can find are pointing to an Alpha version which doesn't fill the user with confidence: http://alpha.neohq.net/docs/java-driver/

**Comment by zhenlineo** [comment]
Sorry for the confusion. Pls use the one here https://github.com/neo4j/neo4j-java-driver/wiki for now.

I will update the old link to the new one

**Comment by graemerocher** [comment]
Note that even http://neo4j.com/docs/api/java-driver/1.0/ refers to it as being a -SNAPSHOT version. Are there no stable releases of the javadocs?

**Comment by graemerocher** [comment]
Also I cannot find the javadoc for `org.neo4j.driver.v1.types.Node` or anything within the `types` package

**Comment by zhenlineo** [comment]
Thanks for pointing the problem out. We are working on the fix for the missing docs. Will let you know once we get the new doc published.

**Comment by zhenlineo** [comment]
The new doc publish now -> http://neo4j.com/docs/api/java-driver/1.0/
