### ISSUE TITLE
Config and ConfigBuilder expose internal interface (Logging)

### ISSUE THREAD

**Issue by rjbaucells** [neo4j/neo4j-java-driver#197]
Config class in package org.neo4j.driver.v1 exposes interface org.neo4j.driver.internal.spi.Logging.

Is package org.neo4j.driver.internal part of the public API?

or

Is it part of the internal implementation?

**Comment by zhenlineo** [comment]
The logging and logger class should be in the public package. Thanks for bring this to us. We will move that to public API. The `internal` package is not public API.

**Comment by zhenlineo** [comment]
Will be part of public api in next 1.0 or 1.1 release
