### ISSUE TITLE
String return in List adds extra "

### ISSUE THREAD

**Issue by callicles** [neo4j/neo4j-java-driver#201]
Using the driver in a scala environment if I do this:

``` scala
// create the object with a list of Strings inside
val javaResults = session.run("CREATE (t:Test {list: ['1']}) RETURN t").list()

// Convert to Scala list
val results = (for (i <- 0 until results.size) yield results.get(i)).toList

val list = results.head.get("t").get("list").asList(Values.ofToString).toList
```

Then the list is a list of Strings with extra `"` ie:

``` scala
list.head == "1" // false
list.head == "\"1\"" // true -> extras "
```

In order to make it work I am using a workaround to remove leading and trailing character for each element of the list.

**Comment by boggle** [comment]
Please use `Values.ofString` instead, it should return the actual String; `Values.ofToString` gives back a human readable representation of the value which for Strings adds quotes around them (as of driver 1.1)

**Comment by callicles** [comment]
My bad, you are right, works like a charm with `Values.ofString`
