### ISSUE TITLE
Issue with Clojure Map Interop

### ISSUE THREAD

**Issue by ducky427** [neo4j/neo4j-java-driver#208]
A Clojure map both implements the interfaces - `java.util.Map` and `java.lang.Iterable`.

Currently while encoding the data, the latter interface is used and not the former. See [`Value.value` method](https://github.com/neo4j/neo4j-java-driver/blob/1.1/driver/src/main/java/org/neo4j/driver/v1/Values.java#L67).

It would be better to use the former. So if value is a instance of Map should be moved up in the method.

Thank you.

**Comment by zhenlineo** [comment]
https://github.com/neo4j/neo4j-java-driver/pull/209
CC @boggle I failed to think of any difference the change in above PR would make to java, but maybe there is another language concerns? What do you think of this topic?

**Comment by ducky427** [comment]
Over the longer term, it would be nice to have a proper mechanism to register how to encode data which the driver doesn't know about.

**Comment by zhenlineo** [comment]
If you really really want to define how you could interpret a data undefined, you might find implementing `AsValue` interface useful. But `AsValue` interface is internal use only, so we will make any promise to keep it same over versions.

**Comment by zhenlineo** [comment]
I am closing this issue as the fix already merged and a release with fix 1.0.5 has already be released.
