### ISSUE TITLE
The drive can be connected neo4j cluster it? 

### ISSUE THREAD

**Issue by okuc** [neo4j/neo4j-java-driver#228]
The drive can be connected neo4j cluster it? Can words, how the connection? Thank you!

**Comment by technige** [comment]
We have no explicit clustering support in the 1.0 version of the driver, you would need to create a separate `Driver` instance for each machine in the cluster.

There is also some information on setting up HAProxy to work with Bolt that you might find useful:
http://neo4j.com/docs/operations-manual/current/deployment/#ha-haproxy

**Comment by zhenlineo** [comment]
@okuc I am closing this issue as I think your question is answered and your problem could be addressed by the documentation given by Nigel. Please be free to reopen this issue or create new ones if you have more questions.

Best,
Zhen
