### ISSUE TITLE
session.close()  hangs

### ISSUE THREAD

**Issue by chrix75** [neo4j/neo4j-java-driver#258]
Hi,

After loading around 600,000 nodes with relations in a Groovy script, the call of session.close() hangs and the scripts never exists.

My query is:

```
def entrepriseQuery = "match (e:Etablissement {siret: {siret}}) " +
        "merge (n:Entreprise {siren: {siren}}) " +
        "with e, n " +
        "merge (e)<-[:EST_SIEGE]-(n)"
```

I use in my project this library org.neo4j.driver:neo4j-java-driver:1.1.0-M06

Thanks

**Comment by zhenlineo** [comment]
Hi,

Sorry for coming you a bit late. Could you give us more info about your problem? Can you run this query via browser successfully without hanging? I am interested to know how long this query takes to finish on the server side.

`session.close()` will not finish if your query did not finish. So if say your query will take 10mins to finish on the server then the `session.close()` will only finish after that.

However if you feel the query is taking too long and you want to kill it, then you could try to use session.reset() to kill this long running query, also you could find in neo4j manual that you could config how long you want a query run on the sever. All query takes long than that will be killed.

Zhen

**Comment by chrix75** [comment]
Hi,

My query hasn't got trouble: individually, the response time is good.
I've solved my problem by using transactions: every 10,000 queries I
commit. By doing that, there is no problem anymore.

Chris

2016-11-14 12:26 GMT+01:00 Zhen Li notifications@github.com:

**Comment by technige** [comment]
Closing as solved by regular commit.
