### ISSUE TITLE
Proper database version to use with current driver?

### ISSUE THREAD

**Issue by FylmTM** [neo4j/neo4j-java-driver#26]
Hi,

Currently I am trying to integrate driver in our solution. 
We use neo4j-harness for integration test layer. I enabled NDP there. Looks like that everything is up-and-running, but I face some strange errors during query execution (it receive non-expected response from server).

Am I right that I should build from source, from latest(master) version of Neo4j to experiment with NDP?

**Comment by FylmTM** [comment]
Update.

Looks like that using master (currently 2.3 branch) version of Neo4j do the trick. Everything (almost) running correctly.

**Comment by jexp** [comment]
Thanks a lot for looking into all of these, your feedback is highly appreciated !!!

**Comment by jakewins** [comment]
@FylmTM +1 on latest master. Both the protocol and this driver are changing day-to-day currently, it'll be a few months before it stabilizes :)
