### ISSUE TITLE
Error with session object leaking

### ISSUE THREAD

**Issue by kevanghobadi** [neo4j/neo4j-java-driver#277]
Hello,

We are getting the error _app="customer360-identity-qa2" log_level="ERROR" thread="Finalizer" Neo4j Session object leaked, please ensure that your application calls the `close` method on Sessions before disposing of the objects._

This seems to happen in proximity to whenever the database goes offline then back online, and we have every single session closed in the finally portion of a try catch block. We are using AKKA reactive streams to get information to the save function and also using the bolt protocol with neo4j. 

Thanks

**Comment by zhenlineo** [comment]
Hi, which version of the driver you are using? Is it 1.0.6? When the database goes offline, will you also close the old driver and then restart a new driver? Or you keep on using the same driver?

**Comment by technige** [comment]
Please can you clarify what action you are hoping for us to take here.

**Comment by nandosola** [comment]
@kevanghobadi are you using `neo4g-ogm` on top? If so, please check https://github.com/neo4j/neo4j-ogm/issues/306 first

**Comment by technige** [comment]
Closed due to lack of information.
