### ISSUE TITLE
Missing getId() method for Node and Relationship values

### ISSUE THREAD

**Issue by FylmTM** [neo4j/neo4j-java-driver#28]
We have compatibility layer - `GraphDatabaseService` implementation. We return nodes with their internal ID's.

Currently, as I see - there is no separate method to retrieve Node/Relationship internal id.

```java
// driver/src/main/java/org/neo4j/driver/internal/messaging/PackStreamMessageFormatV1.java:499
String urn = unpacker.unpackString();
```
I suppose that, currently, id isn't transmitted to client as separate value.
String is returned and then used as identity. This string looks like `node/0`.

So, currently I use such code to extract id:
```java
Node node = value.asNode();
Long.parseLong(node.identity().toString().split("/")[1]) ;
```

Question: is there possibility to acquire ID for node/relationship?

**Comment by jexp** [comment]
I think it is intentional to return opaque node-ids.

It is planned that you can send those id's back to cypher and it will understand them automatically.

**Comment by FylmTM** [comment]
I use this `id` for several internal parts (transaction-scoped cache layer), as it is provided from `Node` interface in `org.neo4j.graph.db` package.

I can't use Node objects provided by driver, because I wan't to keep compatibility between several implementations.

Should I reconsider my architecture to decouple from `id` attribute?

**Comment by jexp** [comment]
Going forward we want id's to be  opaque. So if you treat an id as an `Object` in your cache layer (which has `equals()` and `hashcode()`)  it should be fine.

**Comment by FylmTM** [comment]
@jexp Okey, thanks for explanation. I'll consider this how we can change our implementation.

**Comment by jakewins** [comment]
+1 on what @jexp said, treat ID as an object rather than as a long and you should be good :)

The ID change is one of the big things that's proposed in here, let us know how it works out for you, super important that we don't break stuff doing this. The intention is simply to stop using `long`, since that ties us down in terms of options for generating the ids.
