### ISSUE TITLE
BoltRequest doesn't map enumerated values when executing statements

### ISSUE THREAD

**Issue by dsolmirano** [neo4j/neo4j-java-driver#290]
In the code for `org.neo4j.ogm.drivers.bolt.request.BoltRequest`, lines 142 and below:

```
		BoltTransaction tx;
		try {
			String params = mapper.writeValueAsString(request.getParameters());
			TypeReference<HashMap<String, Object>> typeRef = new TypeReference<HashMap<String, Object>>() {
			};
			HashMap<String, Object> parameterMap = mapper.readValue(params.getBytes(), typeRef);

			LOGGER.info("Request: {} with params {}", request.getStatement(), parameterMap);

			if (transactionManager.getCurrentTransaction() == null) {
				org.neo4j.ogm.transaction.Transaction autoCommitTx = transactionManager.openTransaction();
				tx = (BoltTransaction) autoCommitTx;
				StatementResult statementResult = tx.nativeBoltTransaction().run(request.getStatement(), parameterMap);
				tx.commit();
				tx.close();
				return statementResult;
			}
			tx = (BoltTransaction) transactionManager.getCurrentTransaction();
			return tx.nativeBoltTransaction().run(request.getStatement(), request.getParameters());
```

When `transactionManager.getCurrentTransaction() == null`, the code executes `tx.nativeBoltTransaction().run(...)` with parsed `parameterMap` variable. But for an existing transaction, the same code is called with `request.getParameters()` instead.

The run method eventually uses `org.neo4j.driver.v1.Values.value()`, that fails to parse a non primitive object. My understanding is that using the parsed parameter map should fix the issue.

A way to reproduce this bug is a transactional repository in which one of the methods receives an enum as parameter.

```
@Repository
@Transactional
public interface TestRepository {
   @Query("MATCH (x:RECORD {recordType: {0}}) RETURN x")
   public Set<Record> getRecordsOfType(RecordType recordType);
}

@NodeEntity(label = "RECORD")
public class Record {
    private RecordType recordType;
...
}

public enum RecordType {
...
}
```

**Comment by zhenlineo** [comment]
Hi,

We looked into your issue but it is more a ogm problem. Please raise your problem to ogm for mapping enum to string. The java driver will not support any smart type mapping. The type mapping system will maintain what it is, as simple as possible in this driver.

Cheers,
Zhen

**Comment by dsolmirano** [comment]
Sounds good - What I was trying to say is that the code is calling the same method with different parameters in each side of the if statement, and I'm not sure if that's a bug or intended:

When `getCurrentTransaction() == null`
```
StatementResult statementResult = tx.nativeBoltTransaction().run(request.getStatement(), parameterMap);
```

and outside of the `if` (that executes when there is a transaction):

```
return tx.nativeBoltTransaction().run(request.getStatement(), request.getParameters());
```

**Comment by zhenlineo** [comment]
Hi @dsolmirano Do you mean the code in `org.neo4j.ogm.drivers.bolt.request.BoltRequest`? We do not own this package. It belong `ogm` I think.

Let me know if there is anything else we could help you.

Cheers,
Zhen

**Comment by dsolmirano** [comment]
Do'h. Apologies - I'm definitively looking at the wrong packages. Thanks for pointing me in the right direction!
