### ISSUE TITLE
Values.parameters for Labels and Relationship types

### ISSUE THREAD

**Issue by protheusfr** [neo4j/neo4j-java-driver#296]
Hello,

It seems it is not possible to use Values.parameters system for node labels or relationship types in the current version.

ex : `MATCH (p:people:{contractor_type} {name:{name}})-[:{link_type}]->(something)`
with `contractor_type` and `link_type` as parameters as well as `name`.

Could this be added as futur feature ?

**Comment by technige** [comment]
This is a limitation of Cypher and as such is not under control of the driver software. I'm sure a discussion exists on this in the neo4j/neo4j repo, please check there for more info.
