### ISSUE TITLE
(Bolt) Use of ServiceUnavailableException in TLS-enabled channel

### ISSUE THREAD

**Issue by nandosola** [neo4j/neo4j-java-driver#302]
Hi,

I'm trying to debug a potential issue in [neo4j-ogm](https://github.com/neo4j/neo4j-ogm) that might be related to Bolt session handling after a server restart (see also: spring-projects/spring-data-neo4j#373). Before going any further, I have a doubt concerning the Java Driver:

- For plaintext connections, the first operation after the restart results in a [`ServiceUnavailableException`](https://github.com/neo4j/neo4j-java-driver/blob/1.1/driver/src/main/java/org/neo4j/driver/internal/net/BufferingChunkedInput.java#L420) with the following message:

  > "Connection terminated while receiving data. This can happen due to network instabilities, or due to restarts of the database."

- For TLS-enabled connections,  the first operation after the restart results in a [`ClientException`](https://github.com/neo4j/neo4j-java-driver/blob/1.1/driver/src/main/java/org/neo4j/driver/internal/security/TLSSocketChannel.java#L166) with exactly the same message. 

My question is, why are there two different exceptions instead of just using `ServiceUnavailableException` for both?

----
Just FYI, `neo4j-ogm` doesn't handle `ServiceUnavailableException` yet. It just wraps  `ClientExceptions` coming from server disconnections or network glitches in `CypherException`, so the library user has to catch them and reconnect manually, invoking a new query.

**Comment by zhenlineo** [comment]
We will have a look at this. It should be a ServiceUnavailable for TLS connection too by reading directly.

**Comment by zhenlineo** [comment]
The bug should have been fixed and released in 1.1.2 driver. I am closing this issue but pls let me know if the problem still exists.
