### ISSUE TITLE
Value Types are lost after sending data over the driver

### ISSUE THREAD

**Issue by bHacklv** [neo4j/neo4j-java-driver#307]
## Value Types (Integer and Float) are lost after sending data over the driver,

If I create Node with 4 properties:
* int : 1
* long : 2L
* double : 3.0
* float : 4.0f
I would expect same property types to be returned when retrieved from the server via driver.

**Neo4j Version:** 3.1
**Operating System:** Win7
**API:** neo4j-java-driver 1.1.0

### Steps to reproduce
1. Create Node
2. Assign 4 properties of different types (int, long, double, float)
3. Retrieve each value and evaluate it's type against the initial type

### Expected behavior
property creation type is equal to retrieved property type.

### Actual behavior
int type is retrieved as long
float type is retrieved as double

## Findings
Well, I can see you've got 'value adapter' for **IntegerValue** which in reality combines two types - long and int, and **FloatValue** - both of which extend **NumberValueAdapter.**
When I've created Node and am setting properties - it goes through ```Values.value(propertyValue)``` and transforms my **Integer** into:
```
    private final long val;
    public IntegerValue( long val ) {
        this.val = val;
    }
```
and **Float** into:
```
    private final double val;
    public FloatValue( double val ) {
        this.val = val;
    }
```

_This makes me sad._ So On the server I end up always only persisting long and double typed properties, never int or float.
When I retrieve this properties from the server using ```Node.asMap()``` -> I again _(not surprised)_ get back **IntegerValue** and **FloatValue** which are "transformed" _(just returns their val)_ via ```NumberValueAdapter.asObject() ->  asNumber();``` respectively into Long and Double.

**What is important - this is not compatible with Official Embedded DB and REST**

**Comment by lutovich** [comment]
Hi @bHacklv, thanks for raising this issue.

I think supporting only `double` and `long` in the driver is a deliberate decision. Those are the only two numeric types supported by the Cypher query language, which is the main and only way Bolt driver can interact with the database. It is possible to store other numeric types using embedded and probably REST (did not verify this) but this is mostly for historical reasons. If you go through Cypher, either in driver or via `GraphDatabaseService#execute()` in embedded or via Cypher REST endpoint then only `double` and `long` can appear in the store. @technige could you please confirm this?

Could you please describe the use case when you need more types than `double` and `long`? What kind of problems does this bring?

**Comment by technige** [comment]
This reduction of available data types was indeed a deliberate decision and part of the type system introduced alongside Bolt. The types available at store level are very Java-specific and in order to maximise portability, we dropped those which are least portable. Generally speaking, most users will not be negatively affected by having less control over the number of bytes that actually get written to disk. Indeed, this actually allows us to optimise storage of numbers transparently.

JSON over HTTP was actually worse in this regard. JSON itself, like JavaScript, only technically supports `Number` which is an alias for double.

I am also curious as to what is negatively affected for you by being unable to directly read and write, say, a two byte integer?

**Comment by FylmTM** [comment]
Hi @technige,

Thanks for the explanation.
We are migrating from another database to Neo4j. Because of this, we need to ensure compatibility (rewriting Applications is not an option).

We created our kinda-binary-protocol to use with Neo4j some time ago (when Neo4j was 2.2.x) and used it.
Now we are trying to migrate to Bolt, to use official binary protocol.

But we need to retain type compatibility. If the application is writing integers, then we must return integers.
Same applies to:
* byte
* short
* integer
* float
* array of those

We have tests that verify that `GraphDatabaseService#execute()` respects types.
Query example:
```
CREATE (node:Node) SET node.prop = $prop
```

If we pass an integer into an `execute` params, then integer will be stored in a database.
So, this query will return node with integer property:
```
MATCH (node:Node) RETURN node
```

### Bolt

Documentation for Bolt protocol states that 1-2-4-8 byte integers are supported: http://boltprotocol.org/v1/#ints

So, I am curious is it possible to somehow get access to this functionality?

**Comment by technige** [comment]
I'm afraid that there is no way to achieve this through Bolt and, as this isn't something we see as broken, there are no plans to move away from these type system abstractions. The core Java API of course still provides access to the store-level data types but Cypher itself has no direct concept of any number types other than `CTInteger` and `CTFloat`. See [here](https://github.com/neo4j/neo4j/blob/3.2/community/cypher/frontend-3.2/src/main/scala/org/neo4j/cypher/internal/frontend/v3_2/symbols/type_system.txt) for more details on Cypher types.

The link you've included isn't an official Neo Technology site but that particular detail seems to refer to the PackStream serialisation format used by Bolt messages. The representations there are completely independent from the underlying storage data type. A 64-bit integer in the store may still only require 8 bits for transmission if its value is small enough.

If you need to retain access to the store-level type detail then your only option is to stick to the core Java API.

**Comment by zhenlineo** [comment]
You will still have access to GraphDatabaseService in `procedures`.

If you still want to use bolt drivers for your application, I would recommend you to use `procedures` when writing to database and reading float numbers from the database, and then cast types when reading other data types from database.

**Comment by bHacklv** [comment]
@zhenlineo 
When data comes to the 'server' via procedure - data is already 'converted'... because of bolt.

@lutovich 
By executing this code **I can persists and retrieve value of type Integer (and others) with Embedded via Cypher.**
```java
final GraphDatabaseService graph = serverControls.graph();
try (final Transaction transaction = graph.beginTx()) {
            final Map<String, Object> params = new HashMap<>();
            params.put("prop", 50);

            graph.execute("CREATE (n:Node) set n.prop = $prop", params).close();
            final Result result = graph.execute("MATCH (n:Node) RETURN n.prop AS n");
            final ResourceIterator<Object> n = result.columnAs("n");
            final Integer prop = (Integer) n.next();
}
```

<details>
<summary>Here are some stack traces that show how this happens (<b>click to expand</b>):</summary>

![create-node-set-prop-intval](https://cloud.githubusercontent.com/assets/5772920/22107812/ac1a3472-de58-11e6-8100-7407075f8d34.png)
![readprop-intval](https://cloud.githubusercontent.com/assets/5772920/22107811/ac19e3e6-de58-11e6-9c0c-dd36152a9097.png)
</details><br/><br/><br/>

I appreciate any ideas how I could get away from typed properties...
But bear in mind that if I had something like this:
```java
// example pseudo-code
class SolarPannel {
    int maxPower
    float maxVoltage
    float circuitVoltage
    byte fuseRating
    short weight
    int Status.ordinal() 
/**ordinal of enum. value of enums always stored as ordinal value (int) and enum is retrieved using .values()[ordinalValue]
**/
...
}
```
I can't go away and change everything to long and double...
Otherwise it seems that bolt and this driver are not suitable for my use case.

**Comment by zhenlineo** [comment]
@bHacklv My bad, procedure still only support Cypher types too.

While I would like to suggest you two other options.

### Option 1: Check out https://github.com/neo4j/neo4j-ogm


###  Option 2: In one word, do the type cast yourself when using this driver. 
For writing a data such as a Node, write a Procedure like:
```
void createSolarPannelNode(long maxPower, double maxVoltage ...)
{
    int realMaxPower = (int) maxPower;
    float realMaxVoltage = (float) maxVoltage;
    ...
}
```
For reading data, such as a node, do not use `asMap` but do the cast for each of the properties, such as `Node.get(maxPower).asInt()`.

**Comment by bHacklv** [comment]
@zhenlineo 
Our application acts as a **'middleware'** between Neo4j and complex system (which has sub-systems, etc that write and expect to receive correct types).
Though I gave an example of what sort of Class and its types we would have - **option 1** and **option 2** is a no go for us, as **at our stage we don't have class models** and still operate in _abstract class fashion_ (Nodes, Rels, etc.). So there would be nothing to map to and we still return properties as Object type (expecting them to have at-persist-time types).

I suppose we would have to stay with our own 'driver' solution then.

**Comment by technige** [comment]
Closing issue as now being dealt with separately through customer support channel.
