### ISSUE TITLE
Constraint violated exceptions result in some other bolt transactions hanging

### ISSUE THREAD

**Issue by luanne** [neo4j/neo4j-java-driver#316]
This is a bit difficult to describe, and not sure whether I can write a clean test for it, but here's what is happening. I have a couple of test suites that hang on some tests only if one of the previous tests executed Cypher statements that resulted in a Constraint violation exception. 
When stepping through the hanging test, tx.run returns, but then, `StatementResult.keys()` hangs, specifically in `ConcurrencyGuardingConnection.receiveOne()` -> `delegate.receiveOne()`
Using version 1.1.1

**Comment by lutovich** [comment]
Hi @luanne,

Which neo4j version are you using? Do you by chance have database logs for cases when tests hanged?

Thanks in advance.

**Comment by zhenlineo** [comment]
Besides what @lutovich said.

It sounds to me that your tests are reusing the same driver and maybe the test that hangs is reusing the connection where the Constraint violation exception was thrown?

Could you confirm us that the error did not happen before with 1.1.0 driver (or other versions if you have ever tried), and you did not upgrade server version recently in your tests too?

Thanks,
Zhen

**Comment by luanne** [comment]
Same driver, yes, but definitely different transaction. The server version remains 3.0.8. I'll try with 1.1.0, and try to get you logs as well in the next day or so.

**Comment by lutovich** [comment]
Hi @luanne.

I've tried to reproduce the problem with a simple test like this:

```java
@Test
public void sessionAfterConstraintViolationError()
{
    try ( Driver driver = GraphDatabase.driver( neo4j.uri() ) )
    {
        try ( Session session = driver.session() )
        {
            session.run( "CREATE CONSTRAINT ON (book:Book) ASSERT book.isbn IS UNIQUE" );
        }

        try ( Session session = driver.session() )
        {
            session.run( "CREATE (book:Book {isbn: 'abc'})" );
        }

        Session violatingSession = driver.session();
        violatingSession.run( "CREATE (book:Book {isbn: 'abc'})" );
        try
        {
            violatingSession.close();
            fail();
        }
        catch ( Exception e )
        {
            assertThat( e, instanceOf( ClientException.class ) );
        }

        try ( Session session = driver.session() )
        {
            session.run( "CREATE (book: Book {isbn: 'bca'})" );
        }
    }
}
```

but it did not show up. Did you have a chance to try driver 1.1.0?

**Comment by zhenlineo** [comment]
@luanne Is this issue still bothers you? Could you update us more information on this?

**Comment by luanne** [comment]
@zhenlineo sorry for not responding earlier. I haven't had a chance to try 1.1.0. I'm closing this issue now that I'm back to Http on Neo 3.0.8. I expect to upgrade to Neo 3.1 with the Bolt driver in a month, and I'll reopen if this is still an issue. Thanks.
