### ISSUE TITLE
memory leak in logging usage

### ISSUE THREAD

**Issue by if6was9** [neo4j/neo4j-java-driver#359]
There is a severe memory leak here:

https://github.com/neo4j/neo4j-java-driver/blob/1.3/driver/src/main/java/org/neo4j/driver/internal/NetworkSession.java#L65

Our application ends up in GC hell after running for a few days.  Here is a chart from new relic that shows this:

![image](https://cloud.githubusercontent.com/assets/463742/25280281/428ad2f2-265e-11e7-999a-76f53d7f0ccb.png)

I'll submit a PR shortly.

**Comment by if6was9** [comment]
https://github.com/neo4j/neo4j-java-driver/pull/360

**Comment by lutovich** [comment]
Hello @if6was9,

Java driver 1.2.2 was released yesterday and is now available in maven central. Could you please try it out to confirm that this issue is resolved?

Thanks.

**Comment by lutovich** [comment]
Hello @if6was9,

I'll close this issue assuming that fix in 1.2.2 and 1.3.0 works for you. Attached PR adds a logger count assertion to the stress test. Stress test was showing the same logger leak reported here.

Thanks for reporting this problem!

**Comment by if6was9** [comment]
I believe the issue is resolved.  Thank you.
