### ISSUE TITLE
Need contributors?

### ISSUE THREAD

**Issue by mangrish** [neo4j/neo4j-java-driver#4]
Hey guys,

Do you need any help with this driver? I've done a temporary one waiting for this to come out: https://github.com/inner-loop/java-neo4j-client.  I've built an OGM and would love to hook it up with this!

I would love to help out if i can :)

::mark

**Comment by jakewins** [comment]
Hey mate!

sorry for taking a week to get back, I didn't have notifications set up for this issue tracker properly. 

Contributions are always welcome, and I'd be super keen to get feedback from you on how this fits with an OGM and what is missing! My email is jake [at] neotechnology.com, if you ping me there perhaps we can set up a call?

**Comment by mangrish** [comment]
No problemo! :)

I've hit you back at your email with my details to set up a call :+1:
