### ISSUE TITLE
We should pass the timeouts here (or provide users with the ability to pass the timeout for running query in neo4j)

### ISSUE THREAD

**Issue by meenalc** [neo4j/neo4j-java-driver#421]
https://github.com/neo4j/neo4j-java-driver/blob/7c4406d64fda15a5a5bfd374c883379f23430034/driver/src/main/java/org/neo4j/driver/internal/util/Futures.java#L89

**Comment by lutovich** [comment]
Hi @meenalc,

Could you please explain a bit more why you thing there should be a timeout?

That `future.get()` is called from multiple places and only couple of them actually wait for query results. Having a timeout there is not enough to stop query execution. Timeout will only unblock application thread but IO threads will not stop receiving data from the database. There is currently no way to pass query or transaction timeout from driver to database. It's in our roadmap and will probably require an API change / addition, smth like this would work:

```java
Session session = ...;
Duration maxTxDuration = Duration.ofSeconds(60);
Transaction tx = session.beginTransaction(maxTxDuration);
...
```

I think `Future.get()` without timeout is the same as previous blocking behaviour in 1.4 branch. Driver waits to read / receive data from server without any timeouts.

**Comment by lutovich** [comment]
Closing this issue, transaction timeout is something we plan on adding soon.
