### ISSUE TITLE
Batch insert/update interface/method

### ISSUE THREAD

**Issue by vishwajitmankar** [neo4j/neo4j-java-driver#443]
Sorry if I have missed it while reading doc, however, I didn't find interface to insert bulk data. Our requirement is, we fetch bulk nodes and create relationship with them. Also need to update Node's specific property to mark relationship has been established. Wondering whether Java driver has something like JDBC executeBatch or addbatch.
Thank you

**Comment by lutovich** [comment]
Hi @vishwajitmankar,

Right now driver does not expose any bulk query execution functionality.

I can suggest using either explicit transactions or transaction functions for this.
Executing:
```
transaction.run(query1);
transaction.run(query2);
transaction.run(query3);
```
results in three queries being sent to the database. Driver does not wait for responses, unless they are explicitly consumed.
More details can be found in the [developer manual](https://neo4j.com/docs/developer-manual/current/drivers/sessions-transactions/#driver-transactions-transaction-functions).

Could you please try this out and let us know if it meets your performance expectations?
Thanks!

**Comment by vishwajitmankar** [comment]
I am trying something like this, please let me know if this looks good. I will update thread once I perform load test - 

@Override
	public void writeBulk(final List<String> queries) {
		try ( Session session = driver.session() )
        {
            session.writeTransaction( new TransactionWork<Integer>()
            {
                @Override
                public Integer execute( Transaction tx )
                {
                    return createBulkNodes( tx, queries );
                }
            } );
        }
		
	}
.
.
.
.

 private Integer createBulkNodes(Transaction tx, List<String> queries) {
		
		Iterator<String> queryItr = queries.iterator();
		
		while(queryItr.hasNext()) {
			tx.run(queryItr.next());
		}
		tx.success();
		return 1;
	}

**Comment by lutovich** [comment]
@vishwajitmankar code looks good to me. You could also use `UNWIND` Cypher clause to provide query once with a list of parameters. See [this developer manual section](https://neo4j.com/docs/developer-manual/current/cypher/syntax/parameters/#cypher-parameters-create-multiple-nodes-with-properties).

Example would be:

```java
String query = "UNWIND $props AS properties " +
               "CREATE (n:Person) " +
               "SET n = properties";

List<Map<String,String>> properties = Arrays.asList(
    Collections.singletonMap( "name", "Iron Man" ),
    Collections.singletonMap( "name", "Captain America" ),
    Collections.singletonMap( "name", "Hulk" ),
    Collections.singletonMap( "name", "Thor" ),
    Collections.singletonMap( "name", "Thanos" )
);

Map<String,Object> parameters = Collections.singletonMap( "props", properties );

try ( Session session = driver.session() )
{
    session.writeTransaction( tx -> tx.run( query, parameters ) );

    session.readTransaction( tx ->
    {
        StatementResult result = tx.run( "MATCH (p:Person) RETURN p.name" );
        List<String> names = result.list( record -> record.get( 0 ).asString() );
        System.out.println( names );
        return null;
    } );
}
```

which outputs:

```
[Iron Man, Captain America, Hulk, Thor, Thanos]
```

Hope this helps.

**Comment by vishwajitmankar** [comment]
@lutovich Thank you for the example. My requirement is little different with specific inputs for queries, however, I will definitely plan to use UNWIND feature. 
If you don't mind, one more question on Driver interface use; as I understood, it creates connection pool itself. Should I always have it ready at application layer and reuse it and close it only when application exits? Mine is more of a cron job which runs every 5-10 minutes to insert new nodes, create relationship between thousands of newly independently created nodes. My current implementation is some like below --

public abstract class BaseGraphDBHandler implements AutoCloseable{

	private final Driver driver;

    public BaseGraphDBHandler( String uri, String user, String password )
    {
        driver = GraphDatabase.driver( uri, AuthTokens.basic( user, password ) );
    }

    @Override
	public void close()
    {
        driver.close();
    }
    
    public Driver getDriver() {
    	return driver;
    }
    
    abstract public void read(String query) throws DataDeleteException;
    abstract public void write(String query) throws DataDeleteException;
    abstract public void writeBulk(List<String> queries) throws DataDeleteException;
    abstract public void execute(String query);	
    abstract public void delete(String query);	
}

Client implementation, get instance through Object factory -

try (BaseGraphDBHandler dbHandler = getInstance().getNeo4jBoltDBHandler()){
			dbHandler.write("CREATE (n:NEWDALTEST) return n");
			dbHandler.read("MATCH (n:NEWDALTEST) return n LIMIT 10");
			
			//dbHandler.write("MATCH (n:NEWDALTEST) delete n");
			//dbHandler.close();
		} catch (DataDeleteException e) {
			
		}catch (Exception e){
                  }

Should I be following traditional collection pooling concept and pass/inject Driver object where ever needed. Or above implementation is efficient. Thank you in advance. Appreciate your support.

**Comment by lutovich** [comment]
@vishwajitmankar it is recommended to keep one driver per application, if possible, and reuse it. This might result in better performance because code will only pay the cost of establishing TCP connections once. Driver does keep a connection pool inside.

**Comment by vishwajitmankar** [comment]
I agree. I am moving the driver loading in singleton class and will re-use it. As I said, application works as a scheduler, my only challenge remaining is how I gracefully close Driver in case some kills the process. 
I see Neo4j terminating the connection and logging exception in log, which is kind of relief. There are no open connection hanging around. 
I will post my performance observations after final implementation and testing.

**Comment by vishwajitmankar** [comment]
I did some testing and below are the results, which are not very encouraging

Windows with 16GB RAM, 100K nodes with local connecting to Neo4j.

```
String defaultNodes = "1000";

    if(args.length > 0) {
        defaultNodes = args[0];
    }
String query = "MATCH (n) return n LIMIT "+defaultNodes;

        long time = System.currentTimeMillis();

        session.run(query);

        System.out.println("With bolt for LIMIT "+defaultNodes+" -- "+(System.currentTimeMillis() - time));

        time = System.currentTimeMillis();

        Neo4jRESTHandler dbHandler = new Neo4jRESTHandler();
        dbHandler.executeCypherQuery(query);

        System.out.println("With REST for LIMIT "+defaultNodes+" -- "+(System.currentTimeMillis() - time));
```
C:\Migration>java -jar neo4jtestexamples-1.0.0-SNAPSHOT-jar-with-dependencies.jar

With bolt for LIMIT 1000 -- 131

With REST for LIMIT 1000 -- 162

C:\Migration>java -jar neo4jtestexamples-1.0.0-SNAPSHOT-jar-with-dependencies.ja r

With bolt for LIMIT 1000 -- 143

With REST for LIMIT 1000 -- 156

C:\Migration>java -jar neo4jtestexamples-1.0.0-SNAPSHOT-jar-with-dependencies.ja r 10000

With bolt for LIMIT 10000 -- 377

With REST for LIMIT 10000 -- 156

C:\Migration>java -jar neo4jtestexamples-1.0.0-SNAPSHOT-jar-with-dependencies.ja r 10000

With bolt for LIMIT 10000 -- 335

With REST for LIMIT 10000 -- 157

C:\Migration>java -jar neo4jtestexamples-1.0.0-SNAPSHOT-jar-with-dependencies.ja r

With bolt for LIMIT 1000 -- 104

With REST for LIMIT 1000 -- 161

C:\Migration>java -jar neo4jtestexamples-1.0.0-SNAPSHOT-jar-with-dependencies.ja r 25000

With bolt for LIMIT 25000 -- 595

With REST for LIMIT 25000 -- 155

C:\Migration>java -jar neo4jtestexamples-1.0.0-SNAPSHOT-jar-with-dependencies.ja r 25000

With bolt for LIMIT 25000 -- 544

With REST for LIMIT 25000 -- 151

**Comment by jexp** [comment]
I think in both cases you should also consume the query results.

**Comment by vishwajitmankar** [comment]
I am doing that, this was just to test how much response time same query takes REST vs Bolt.

**Comment by vishwajitmankar** [comment]
I did few more test with large data (100K+) nodes with MATCH, SET AND CREATE options. Also ran program with Page cache, Heap size setting. Below are results - Bolt driver Vs REST call -

```
"MATCH (source:SPARKDATA) where not exists(source.commitID) return source LIMIT 1000"

String query1 = "MATCH (source:SPARKDATA {uuid: $uuid}) SET source.commitID = $commitID";
String query2 = "CREATE (n:GIT:RAW) set n.toolName = 'GIT', n.commitID = $commitID";

try ( Session session = dbHandler.getSession() )
						{
						    session.writeTransaction( tx -> tx.run( query1, parameters("commitID",commitID,"uuid",uuid) ) );
						    session.writeTransaction( tx -> tx.run( query2, parameters("commitID",commitID) ) );
						}

					
					--- UNWIND query for Bolt
					Map<String,Object> sparkParameters = Collections.singletonMap( "props", sparkDataproperties );
					
					Map<String,Object> gitParameters = Collections.singletonMap( "props", gitProperties );
					
					String query1 = "UNWIND $props AS properties " +
				               "MATCH (source:SPARKDATA { uuid: properties.uuid}) " +
				               "SET source.commitID = properties.commitID";
					
					String query2 = "UNWIND $props AS properties " +
				               "CREATE (n:GIT:RAW) " +
				               "SET n = properties";
					
					try ( Session session = dbHandler.getSession() )
					{
						//System.out.println("sparkdata -"+(new Date()));
					    session.writeTransaction( tx -> tx.run( query1, sparkParameters ) );
					   /// System.out.println("sparkdata end -"+(new Date()));
					    session.writeTransaction( tx -> tx.run( query2, gitParameters ) );
					    //System.out.println("gitdata end -"+(new Date()));
					}
```
Same UNWIND queries were used for REST call too.


usingBolt started transaction for loop ... 
Total time taken MATCH query usingBolt -- 126
Total records created and updated -- 1000
Total time taken -- 145393
usingBolt ended... 

usingBolt using UNWIND query started.... 
usingBoltUNWIND Total records created and updated -- 1000
usingBoltUNWIND Total time taken -- 58642
usingBoltUNWIND ended.... 

usingREST using UNWIND query started.... 
Total time taken MATCH query usingREST -- 676
Total records created and updated -- 1000
Total time taken -- 60814
usingREST ended... 


usingBolt started transaction for loop ... 
Total time taken MATCH query usingBolt -- 188
Total records created and updated -- 2000
Total time taken -- 274460
usingBolt ended... 

usingBolt using UNWIND query started
usingBoltUNWIND Total records created and updated -- 2000
usingBoltUNWIND Total time taken -- 113227
usingBoltUNWIND ended.... 

usingREST using UNWIND query started.... 
Total time taken MATCH query usingREST -- 422

INFO: Closing the connection pool
Total records created and updated -- 2000
Total time taken -- 117445
usingREST ended...

**Comment by vishwajitmankar** [comment]
Closing this issue as original question was answered.
