### ISSUE TITLE
Can't specify access mode for begin/end transactions

### ISSUE THREAD

**Issue by jameskleeh** [neo4j/neo4j-java-driver#455]
Currently in GORM we use `beingTransaction` (https://github.com/neo4j/neo4j-java-driver/blob/1.6/driver/src/main/java/org/neo4j/driver/internal/NetworkSession.java#L193) to create transactions. We would like the ability to specify if the transaction is read only, however that is only possible by using a `TransactionWork` object, which is not a pattern we can support currently.

This issue is a feature request to allow the usage of `beginTransaction` with the ability to specify an access mode.

Thanks!

**Comment by lutovich** [comment]
Hi @jameskleeh,

It is also possible to specify access mode when creating a session `Driver#session(AccessMode)`. Then created transaction will inherit the specified access mode. Do you think this solves the problem?

Please note that access mode is not directly translated to transaction "permissions". It is used for routing in a causal cluster to decide which machine should execute query or transaction. So it will have no effect on single instance database. Some more details about this [here](https://neo4j.com/docs/developer-manual/current/drivers/sessions-transactions/#driver-transactions-access-mode).

**Comment by jameskleeh** [comment]
@lutovich Thanks for the reply. I'm aware you can specify the mode for the session, however that would mean I would have to maintain multiple sessions. Unfortunately that is something I fear would cause future issues. I'm roughly familiar with how the access mode is used. If you can consider adding the access mode as a parameter to `beginTransaction`, that would make everything much easier.

Thanks!

**Comment by lutovich** [comment]
@jameskleeh could you please share a link to the code where this functionality would be useful?

**Comment by jameskleeh** [comment]
@lutovich Sure! In GORM we create the transaction here. https://github.com/grails/gorm-neo4j/blob/master/grails-datastore-gorm-neo4j/src/main/groovy/org/grails/datastore/gorm/neo4j/Neo4jTransaction.groovy#L47

We have access to the transaction definition, which has the notion of a read only transaction. We would like to use those semantics in the context of Neo4j to indicate the access mode that should be used.

**Comment by amadfida** [comment]
+1 this would also benefit us greatly as we are a big GORM user and haven't been able to use casual clustering yet.

**Comment by technige** [comment]
From reading your code, I think you may have misunderstood how sessions are intended to be used. The purpose of a session is to provide a convenient logical grouping of causally-chained transactional units of work within a small scope. Sessions are not intended to be passed around or shared across threads and should be considered cheap and disposable. Sessions borrow connections from the driver connection pool as required.

Therefore, I'd recommend refactoring your code to inject the driver instance into the `Neo4jTransaction` class rather than a session instance. Then, where you want to carry out work, wrap each transaction within a session. This session can obviously then accept the access mode.

**Comment by technige** [comment]
Additionally, if you need to causally chain multiple sessions, this can be achieved by manual propagation of bookmarks between sessions.

**Comment by technige** [comment]
Is that approach working for you?

**Comment by amadfida** [comment]
@technige @jameskleeh  has made the modification, initial tests look ok, however we need to do a more detail testing and we are working on it. 

At this point its not a neo4j driver issue so if you need to close this issue out you can.
