### ISSUE TITLE
On exceptions, a wrong ExplicitTransaction instance might get flagged as FAILED

### ISSUE THREAD

**Issue by jsolari56** [neo4j/neo4j-java-driver#487]
I'm getting the following exception:

org.neo4j.driver.v1.exceptions.ClientException: No more interaction with this session is allowed as the current session is already closed or marked as closed. You get this error either because you have a bad reference to a session that has already be closed or you are trying to reuse a session that you have called `reset` on it.

I logged the execution of ExplicitTransaction code where the status is changed with the ExplicitTransacion instance, the new State and the thread name and it went as:

org.neo4j.driver.internal.ExplicitTransaction@7c71fade State:INIT http-nio-8080-exec-1
org.neo4j.driver.internal.ExplicitTransaction@7c71fade State:MARKED_SUCCESS http-nio-8080-exec-1
org.neo4j.driver.internal.ExplicitTransaction@7dff21d0 State:MARKED_SUCCESS http-nio-8080-exec-4
org.neo4j.driver.internal.ExplicitTransaction@7c71fade State:SUCCEEDED http-nio-8080-exec-1
org.neo4j.driver.internal.ExplicitTransaction@7dff21d0 State:SUCCEEDED http-nio-8080-exec-4
org.neo4j.driver.internal.ExplicitTransaction@22f62dce State:INIT http-nio-8080-exec-1
org.neo4j.driver.internal.ExplicitTransaction@2f240df1 State:INIT http-nio-8080-exec-4
org.neo4j.driver.internal.ExplicitTransaction@22f62dce State:MARKED_SUCCESS http-nio-8080-exec-1
org.neo4j.driver.internal.ExplicitTransaction@2f240df1 State:MARKED_SUCCESS http-nio-8080-exec-4
org.neo4j.driver.internal.ExplicitTransaction@22f62dce State:SUCCEEDED http-nio-8080-exec-1
org.neo4j.driver.internal.ExplicitTransaction@2f240df1 State:SUCCEEDED http-nio-8080-exec-4
org.neo4j.driver.internal.ExplicitTransaction@4b66cc58 State:INIT http-nio-8080-exec-2
org.neo4j.driver.internal.ExplicitTransaction@4b66cc58 State:MARKED_SUCCESS http-nio-8080-exec-2
org.neo4j.driver.internal.ExplicitTransaction@4b66cc58 State:SUCCEEDED http-nio-8080-exec-2
org.neo4j.driver.internal.ExplicitTransaction@79e8e4ec State:INIT http-nio-8080-exec-2
org.neo4j.driver.internal.ExplicitTransaction@24b58012 State:INIT pool-133-thread-1
org.neo4j.driver.internal.ExplicitTransaction@63a616ad State:INIT BxIndexRetryableTask-16
org.neo4j.driver.internal.ExplicitTransaction@63a616ad State:MARKED_SUCCESS BxIndexRetryableTask-16
org.neo4j.driver.internal.ExplicitTransaction@63a616ad State:SUCCEEDED BxIndexRetryableTask-16
org.neo4j.driver.internal.ExplicitTransaction@491d871b State:INIT BxIndexRetryableTask-17
org.neo4j.driver.internal.ExplicitTransaction@491d871b State:MARKED_SUCCESS BxIndexRetryableTask-17
org.neo4j.driver.internal.ExplicitTransaction@491d871b State:SUCCEEDED BxIndexRetryableTask-17
org.neo4j.driver.internal.ExplicitTransaction@607b7192 State:INIT BxIndexRetryableTask-18
org.neo4j.driver.internal.ExplicitTransaction@22f50bdb State:INIT BxIndexRetryableTask-19
org.neo4j.driver.internal.ExplicitTransaction@607b7192 State:MARKED_SUCCESS BxIndexRetryableTask-18
org.neo4j.driver.internal.ExplicitTransaction@70515290 State:INIT BxIndexRetryableTask-20
org.neo4j.driver.internal.ExplicitTransaction@35d5248f State:INIT BxIndexRetryableTask-21
org.neo4j.driver.internal.ExplicitTransaction@607b7192 State:SUCCEEDED BxIndexRetryableTask-18
org.neo4j.driver.internal.ExplicitTransaction@70515290 State:MARKED_SUCCESS BxIndexRetryableTask-20
org.neo4j.driver.internal.ExplicitTransaction@24b58012 State:FAILED BxIndexRetryableTask-19
org.neo4j.driver.internal.ExplicitTransaction@70515290 State:SUCCEEDED BxIndexRetryableTask-20
org.neo4j.driver.internal.ExplicitTransaction@24b58012 Throwing Client Exception BxIndexRetryableTask-21
org.neo4j.driver.internal.ExplicitTransaction@22f50bdb State:MARKED_FAILED BxIndexRetryableTask-19
org.neo4j.driver.internal.ExplicitTransaction@24b58012 Throwing Client Exception pool-133-thread-1
org.neo4j.driver.internal.ExplicitTransaction@35d5248f State:MARKED_FAILED BxIndexRetryableTask-21
org.neo4j.driver.internal.ExplicitTransaction@22f50bdb State:ROLLED_BACK BxIndexRetryableTask-19
org.neo4j.driver.internal.ExplicitTransaction@35d5248f State:ROLLED_BACK BxIndexRetryableTask-21

The thread BxIndexRetryableTask-19 flagged the ExplicitTransaction@24b58012 instance as FAILED, but that thread initialized org.neo4j.driver.internal.ExplicitTransaction@22f50bdb instance
After that pool-133-thread-1, who had initialized ExplicitTransaction@24b58012, found the FAILED state and throws the exception.

We use 1.4.6, but 1.5.1 has the same issue.

**Comment by lutovich** [comment]
Hi @jsolari56,

Mentioned `ClientException` can only be thrown by a `Session` that has been explicitly closed. Sessions are single-use only and not thread-safe, same as transactions.

It is a little bit unclear to me why do you track `ExplicitTransaction` instances while the error comes from `NetworkSession`. Could you please explain a bit more?

Listing of interactions with `ExplicitTransaction@24b58012` says it was used by three different threads. Do you ever share sessions and transactions between threads?

It would be super helpful to have a small java program that reproduces the problem. Do you think you could share one?

**Comment by jsolari56** [comment]
Hi @lutovich 

Thank you for your fast response.

Mmm... I don't know if sessions are shared... actually, we don't use the driver directly but through gorm-neo4j plugin. I opened a ticket there.

https://github.com/grails/gorm-neo4j/issues/74

Lets see what they say.

**Comment by lutovich** [comment]
@jsolari56 are `BxIndexRetryableTask` threads handled by the application?
Could you please create a small application for us to reproduce the problem?

**Comment by jsolari56** [comment]
I wasn't able to reproduce the issue in a small application, but I finally found that we were sharing a domain object between threads. I change that code and the issue was gone. Thank you for your hint!.
