### ISSUE TITLE
Unsupported authentication token, scheme 'none' is only allowed when auth is disabled.

### ISSUE THREAD

**Issue by ishaanmadan19** [neo4j/neo4j-java-driver#519]
Not sure how to get around this error. Below is the script I am running:

**object Main extends App{
  val conf = new SparkConf().setAppName("SparkWithNeo").setMaster("local").set("spark.executor.memory","4g")
  val sc = new SparkContext(conf)

  val driver = GraphDatabase.driver("bolt://localhost:7687", AuthTokens.basic("my_username", "my_pwd"))
  val session = driver.session

  val neo = Neo4j(sc)
  val rowRDD = neo.cypher("MATCH (n:Person) RETURN n.name as name limit 10").loadRowRdd
  rowRDD.map(t => "Name: " + t(0)).collect.foreach(println)
  

}**

Anyone have any ideas?

**Comment by lutovich** [comment]
Hi @ishaanmadan19,

You do not need to declare a separate driver and start a session. Spark connector will do this for you. Credentials for it should be set like described here: https://github.com/neo4j-contrib/neo4j-spark-connector#config. I think when credentials are not set in the config, connector tries to use `AuthTokens.none()` while database requires authentication. The separately created driver is not used by the Spark connector.

Hope this helps!

**Comment by lutovich** [comment]
It should also be possible to pass credentials through `SparkContext` like this:

```scala
val config = new Config()
config.set(Neo4jConfig.prefix + "url", "bolt://localhost")
config.set(Neo4jConfig.prefix + "user", "neo4j")
config.set(Neo4jConfig.prefix + "password, "myPassword")
val sparkContext = SparkContext(config)
```

**Comment by mitakshgupta** [comment]
@lutovich - If I try to pass the config parameter to SparkContext's constructor, then it give me the error "error: org.apache.spark.SparkContext.type does not take parameters". Any pointers on this?

**Comment by lutovich** [comment]
@mitakshgupta can you share a code snippet that shows the problem?

**Comment by mitakshgupta** [comment]
@lutovich - I had to change the code to use the SparkSession like

```
import org.neo4j.spark._
import org.apache.spark._
import org.graphframes._
import org.apache.spark.sql.SparkSession

val config = new SparkConf()

config.set(Neo4jConfig.prefix + "url", "bolt://neo4j:root@localhost")
config.set(Neo4jConfig.prefix + "user", "neo4j")
config.set(Neo4jConfig.prefix + "password", "neo4j")

val sparkSession :SparkSession = SparkSession.builder.config(config).getOrCreate()

val neo = Neo4j(sparkSession.sparkContext)
```

Looks like I am able to pass the config now but the error is still the same, "Unsupported authentication token, scheme 'none' is only allowed when auth is disabled". How did you resolve this in your project?

**Comment by lutovich** [comment]
@mitakshgupta looks like you have different username and password both in the URL and in the config values. This test code works for me locally:

```scala
import org.apache.spark.SparkConf
import org.apache.spark.sql.SparkSession

object Main {

  def main(args: Array[String]): Unit = {
    val config = new SparkConf()

    config.set("spark.master", "local")
    config.set(Neo4jConfig.prefix + "url", "bolt://localhost")
    config.set(Neo4jConfig.prefix + "user", "neo4j")
    config.set(Neo4jConfig.prefix + "password", "test")

    val sparkSession: SparkSession = SparkSession.builder.config(config).getOrCreate()

    try {
      val neo4j = Neo4j(sparkSession.sparkContext)
      val count = neo4j.nodes("MATCH (n) RETURN n", Map.empty).loadRowRdd.count
      println(s"count = $count")
    } finally {
      sparkSession.close()
    }
  }
}
```

**Comment by mitakshgupta** [comment]
@lutovich - Thanks for responding. Changing the username and password didn't work for me. And I am still seeing the same error, even after changing my code to replicate the code you gave as an example.

```
import org.neo4j.spark._
import org.apache.spark._
import org.graphframes._
import org.apache.spark.sql.SparkSession
var arr = Array("main","method")
Main.main(arr)

object Main {

  def main(args: Array[String]): Unit = {
    val config = new SparkConf()

    config.set("spark.master", "local")
    config.set(Neo4jConfig.prefix + "url", "bolt://localhost")
    config.set(Neo4jConfig.prefix + "user", "neo4j")
    config.set(Neo4jConfig.prefix + "password", "neo4j")

    val sparkSession: SparkSession = SparkSession.builder.config(config).getOrCreate()
    try {
      val neo4j = Neo4j(sparkSession.sparkContext)
      val count = neo4j.nodes("MATCH (n) RETURN n", Map.empty).loadRowRdd.count
      println(s"count = $count")
    } finally {
      sparkSession.close()
    }
  }
}
```

Does this code look ok to you? Although I haven't made any changes to my Neo4j's configuration, could it be some configuration related issue at my end?

Also, I am new to Scala, so please pardon any mistakes on that front.

**Comment by mitakshgupta** [comment]
@lutovich - Hi, did you get a chance to have a quick look at the code snippet I shared above?

**Comment by lutovich** [comment]
@mitakshgupta the code snippet looks good to me. Can you connect to the same database using neo4j-browser or cypher-shell using the same credentials? Which version of neo4j-spark-connector are you using?

**Comment by mitakshgupta** [comment]
@lutovich - Yes, I have verified and the credentials are correct. And the spark-connector version is 2.1.0-M4. What version are you using?

**Comment by lutovich** [comment]
@mitakshgupta I was running that code with neo4j-spark-connector 2.4.0-M6
