### ISSUE TITLE
Crashes when using the class JULogger.

### ISSUE THREAD

**Issue by Mozhan** [neo4j/neo4j-java-driver#520]
**Neo4j Version:** 1.6.2
**Operating System:** Ubuntu 16.04.4 LTS, McOs High Sierra  (version 10.13.5)
**Machine:**  single machine (laptop)
**Junit version:**  4.12

### Steps to reproduce
Please run the attached test suite for the class org.neo4j.driver.internal.logging.JULogger. 

[JULoggerTestSuite.txt](https://github.com/neo4j/neo4j-java-driver/files/2235979/JULoggerTestSuite.txt)

### Actual behavior
Each test case triggers a unique crash due to how data are forwarded to the JDK APIs (String.format(...)).

### Possible fixes
Before calling the String.format(String format, Object... args)', there should be some checks about the values for `format` and `args`.

**Comment by lutovich** [comment]
Hi @Mozhan,

I can see exceptions like `java.util.MissingFormatArgumentException: Format specifier '%S'` when running the provided test suite. `JULogger` is not meant to be a generic logging utility. It is a class used internally by the driver. Log statements in the driver always have correct string format and arguments. User code should never log using `JULogger` and it lives in an internal package `org.neo4j.driver.internal.logging`.

Does this affect your application that uses this driver? Could you please provide a real-world test that exhibits the same behaviour?

**Comment by Mozhan** [comment]
Hi @lutovich 

The tests I provided come from a static analysis prototype I have been working on as part of a research project. The tool analyses a specified dependency of a project to identify risky API calls which may potentially lead to runtime exceptions. Runtime exceptions may occur either because 1) an API is lacking sufficient documentation, or 2) usage of the API does not conform to the specification, or 3) API wrapper does not indicate the API specification as part of its own specification. The prototype then automatically generates test cases which show how such exceptions may be triggered.

I have been using the tool on various open source projects as part of my preliminary evaluation. In the case of `neo4j-java-driver`, the tool analysed `JDK` APIs. It turned out that it is possible to pass malformed strings to `JULogger` which lead to runtime exceptions. Since the specification for `String.format` includes the requirements on the forwarded arguments, it is the usage of the API in `JULogger` which seems to lack either documentation or checks on the values forwarded to String.format.

I understand that in the internal usage of `JULogger`, the likelihood of passing malformed strings may be low. As part of my preliminary evaluation, it is interesting for me to see if you would agree that adding documentation or checks on the forwarded values would help to prevent potential exceptions?

**Comment by lutovich** [comment]
Hi @Mozhan,

I think adding notes about this to javadoc in `org.neo4j.driver.v1.Logger` would be the best things to do. Internal class `JULogger` implements this public interface. Users of the driver might want to provide a different implementation and documented message template format could be helpful.

**Comment by Mozhan** [comment]
I see and agree. Thank you very much @lutovich. I am closing the issue.

**Comment by lutovich** [comment]
Hi @Mozhan,

Javadocs for message template format were improved in this commit https://github.com/neo4j/neo4j-java-driver/commit/2ca0dfb1d54a202a28ae623ba2c93bb637a7fa1d. Thanks for reporting this!
