### ISSUE TITLE
neo4j-java-driver-1.4.0 already connected to neo4j successfully, but an error occured on the first request visit after a period of no access to the neo4j.

### ISSUE THREAD

**Issue by Yokako** [neo4j/neo4j-java-driver#544]
neo4j-java-driver-**1.4.0**

1. **Premise** :   The driver is connected to neo4j successfully

2. **Error**:         An error occured on the first request visit after a period of no access to the neo4j.

The detail log( **debug.log** in neo4j database ) is as follows:

org.neo4j.driver.internal.net.SocketConnection SocketConnection.java 172 flush
org.neo4j.driver.internal.net.ConcurrencyGuardingConnection ConcurrencyGuardingConnection.java 151 flush
org.neo4j.driver.internal.net.pooling.PooledSocketConnection PooledSocketConnection.java 170 flush
org.neo4j.driver.internal.NetworkSession NetworkSession.java 116 run
org.neo4j.driver.internal.NetworkSession NetworkSession.java 106 run
org.neo4j.driver.internal.NetworkSession NetworkSession.java 94 run
org.neo4j.driver.internal.NetworkSession NetworkSession.java 74 run
java.lang.Thread Thread.java 745 run
Error Message:Unable to send messages to server: Connection reset by peer

**Comment by zhenlineo** [comment]
Hi @Yokako 
Could you upgrade to a newer driver version?

We've introduced maximum transaction lifetime to avoid the problems that you described. 
You can read more in our [docs](https://neo4j.com/docs/developer-manual/current/drivers/client-applications/#driver-config-connection-pool-management)

The most recent stable driver version 1.7.0. There is no API changes from 1.4 to 1.7, except that a lot of more methods and configuration options are added.

**Comment by Yokako** [comment]
> Hi @Yokako
> Could you upgrade to a newer driver version?
> 
> We've introduced maximum transaction lifetime to avoid the problems that you described.
> You can read more in our [docs](https://neo4j.com/docs/developer-manual/current/drivers/client-applications/#driver-config-connection-pool-management)
> 
> The most recent stable driver version 1.7.0. There is no API changes from 1.4 to 1.7, except that a lot of more methods and configuration options are added.

Thanks for replying! 
which method is included in ConfigBuilder do you mean, "maximum transaction lifetime" you referred ?

**Comment by Yokako** [comment]
> Hi @Yokako
> Could you upgrade to a newer driver version?
> 
> We've introduced maximum transaction lifetime to avoid the problems that you described.
> You can read more in our [docs](https://neo4j.com/docs/developer-manual/current/drivers/client-applications/#driver-config-connection-pool-management)
> 
> The most recent stable driver version 1.7.0. There is no API changes from 1.4 to 1.7, except that a lot of more methods and configuration options are added.

And are you Chinese? Can I communicate with you in  Chinese?

**Comment by zhenlineo** [comment]
@Yokako 
To set the maximum connection timeout, the method is `ConfigBuilder#withMaxConnectionLifetime`.

The driver holds a connection pool to avoid the cost of establishing new connections for each transaction. The problem you described in the issue indicates that inside your system, something kills idle connections after a certain timeout _T_. To avoid using dead connections, you can set driver's maximum connection lifetime to be less than _T_.

The following code sets the maximum connection lifetime to 30 minutes. This setting is only available in newer driver versions.
```
public ConfigConnectionPoolExample( String uri, String user, String password )
{
    driver = GraphDatabase.driver( uri, AuthTokens.basic( user, password ), Config.build()
            .withMaxConnectionLifetime( 30, TimeUnit.MINUTES )
            .toConfig() );
}
```

I am closing this issue as it is very straightforward to me that the problem shall be solved with maximum connection timeout. Pls be free to re-open the issue if it still persists. 

You can wrote me in Chinese. Though other maintainers of this driver might not be able to reply to you. 

Cheers,
Zhen

**Comment by Yokako** [comment]
> I am closing this issue as it is very straightforward to me that the problem shall be solved with maximum connection timeout. Pls be free to re-open the issue if it still persists.

OK, THANK YOU!
I will upgrade driver to 1.7.0 and have a try.

**Comment by Yokako** [comment]
@zhenlineo Thanks for your advice!
The solution you suggest really came into effect and solved my problem  after several days of testing.

**Comment by Yokako** [comment]
@zhenlineo 
Hi, Zhen LI, 
      I have another persistent problem. I don't know whether it's related to neo4j-driver usage.

**Problem:**
There is a problem always in the neo4j databases debug.log（**neo4j-community-3.2.3/logs/debug.log**） file.
And  keep printing the the problem log all the time.

**Error Log:**
2018-11-15 07:53:42.892+0000 WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. Connection reset by peer
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zhenlineo** [comment]
@Yokako It could be Neo4j browser or some other app that use driver inside that does not shut down connection cleanly (calling `driver.close()`) when the app is closed. In newer versions of the server, we removed the stacktrace of this exception.

**Comment by Yokako** [comment]
> @Yokako It could be Neo4j browser or some other app that use driver inside that does not shut down connection cleanly (calling `driver.close()`) when the app is closed. In newer versions of the server, we removed the stacktrace of this exception.

@zhenlineo 
The server only conncected by my code with neo4j-java-driver.
But the driver instance used in code is keep-alive, and  I will not close it.
Is this reason for the problem in debug.log?

**Comment by zhenlineo** [comment]
@Yokako We do suggest one driver in an application. But when the application is shutting down, we expect `driver.close` is called to close all resources the driver is holding such as connections. Otherwise, you will have the stacktrace left in your server logs.
