### ISSUE TITLE
memory leak with "node.key IN keys" query?

### ISSUE THREAD

**Issue by tolomaus** [neo4j/neo4j-java-driver#551]
Hi,

I'm using neo4j 3.4 with the neo4j java driver 1.7.2 in a scala play app running on centos 7

I encountered a very strange memory leak issue with the following query:
```
 MATCH (company:Company)
 WHERE company.vat IN {vats}
 RETURN company
```

The session.run works fine but as soon as I want to start consuming the results the application hangs for a couple of minutes during which the memory usage increases with several 100's of MB and finally a GC error is thrown (the app only has limited free memory but that should still largely be enough for what it needs to do).

When I change the query to:
```
UNWIND {vats} as vatToFind
MATCH (company:Company {vat: vatToFind})
RETURN company
```
things work just fine.

Also, running the app on my mac works just fine and running the same query (the first one with the IN statement) on the neo4j web interface works fine.

I'm not even sure the issue is with the driver, it could as well be serverside or even a version conflict between the two.

Any idea what's going on here?

**Comment by zhenlineo** [comment]
@tolomaus What your java/scalar code looks like to run and consume the results of the "IN query" using java driver?

Where is your Neo4j server hosted? Is it hosted with the driver on the centos 7 machine together?

Have you tried to run the same query against the server on centos 7 via browser? Will your browser also hangs too?

**Comment by tolomaus** [comment]
Hi Zhen,

My code looks like this :
```
      session
        .run(
          """
           UNWIND {vats} as vatToFind
           MATCH (company:Company {vat: vatToFind})
           WHERE NOT company.deleted OR {showHistory}
           RETURN company
          """.stripMargin
          , Map[String, AnyRef]("vats" -> vats.asJava, "showHistory" -> showHistory.asInstanceOf[AnyRef]).asJava
        )
        .asScala
        .toArray
        .map { record => convertNodeToCompany(record.get("company").asNode, language) }
```

As you can see I already switched to the UNWIND variant of the cypher query but other than that the scala code was exactly the same for the "IN" query. I tried many different alternatives to consume the results but without success. Even a `simplesession.run(...).next()` already triggered the issue.
 
My neo4j server is hosted on aws ec2, it contains both the app and the db.
Yes running the query via the browser gave instant results, I tried with 1000 items in the list and that took < 1 sec, as expected.

Thanks

**Comment by zhenlineo** [comment]
Hi again,

I can not tell what went wrong with the info we have so far.

Can you do a `explain` on the two queries to get their execution plans? (Just add EXPLAIN in front of the cypher query), then you can print the plan with java driver with `result.summary().plan().toString()`. 

A read query will be lazily executed when pulling the result. So it could just be the query is very slow to run. 

Finally can you take a thread dump both on neo4j and your app when the problem happens?

**Comment by zhenlineo** [comment]
Hi @tolomaus Have you got any chance to to update us more on this issue by trying out the two approaches in my last comment?

**Comment by zhenlineo** [comment]
Hi @tolomaus,

I am closing this issue due to lacking of information to continue. Pls come back to us when you got more inputs for us to continue with this issue.

Cheers,
Zhen

**Comment by tolomaus** [comment]
Oops sorry for not getting back to you, this issue got off my radar.
