### ISSUE TITLE
full text search not working

### ISSUE THREAD

**Issue by deflorilemarului** [neo4j/neo4j-java-driver#599]
CALL db.index.fulltext.queryNodes NOT working from Java but it does from Neo4j Desktop.

(Index has been created, procedure enabled from neo config)

CALL db.index.fulltext.queryNodes('stream', 'Johnson') YIELD node, score  
WITH node as s   
RETURN  s.name as name, s.style as style

this returns in the log
2019-05-11 10:45:55,653 DEBUG [Neo4jDriverIO-2-2] [org.neo4j.driver.internal.logging.Slf4jLogger:debug:75] - [0x59b9ff42][bolt-13] C: PULL_ALL
2019-05-11 10:45:55,657 DEBUG [Neo4jDriverIO-2-2] [org.neo4j.driver.internal.logging.Slf4jLogger:debug:75] - [0x59b9ff42][bolt-13] S: SUCCESS {fields=["name", "style"] t_first=2}
8.438: Application time: 0.0092130 seconds
2019-05-11 10:45:55,658 DEBUG [Neo4jDriverIO-2-2] [org.neo4j.driver.internal.logging.Slf4jLogger:debug:75] - [0x59b9ff42][bolt-13] S: SUCCESS {type="r", t_last=0}
2019-05-11 10:45:55,658 DEBUG [Neo4jDriverIO-2-2] [org.neo4j.driver.internal.logging.Slf4jLogger:debug:75] - [0x59b9ff42][bolt-13] C: COMMIT
2019-05-11 10:45:55,660 DEBUG [Neo4jDriverIO-2-2] [org.neo4j.driver.internal.logging.Slf4jLogger:debug:75] - [0x59b9ff42][bolt-13] S: SUCCESS {bookmark="neo4j:bookmark:v1:tx898"}

but the statement result object seems to be empty of content:

@Override
public String execute(Transaction tx) {
	StatementResult result = tx.run(cql, paramHm);
         while(result.hasNext()){             <---- this is SKIPPED, so no results
	    Record rec = result.next();
         .....
The same java code, if i just do a simple "match(n:Node)return n" returns correctly a list.
Any known issues around this ?
Does the fulltextsearch return another type of statement that i need to use?

Does the java driver support fulltextsearch ? or prepared statements with apoc ?

Thanks

**Comment by zhenlineo** [comment]
Hi @deflorilemarului 

I created a test to run the following query using 1.7 java driver against a 3.5 single instance:
```
try ( Session session = driver.session() )
{
    session.run( format( "CALL db.index.fulltext.createNodeIndex('%s', %s, %s )", "stream", "['Person']", "['name']" ) ).consume();
    session.run( "CALL db.index.fulltext.awaitIndex('stream')" ).consume();
    session.run( "CREATE (john:Person {name: 'John Johnson'})" ).consume();
    StatementResult result = session.run(
            "CALL db.index.fulltext.queryNodes('stream', 'Johnson') " +
                    "YIELD node, score WITH node as s " +
                    "RETURN s.name as name, s.style as style" );
    Record record = result.single();
    assertThat( record.get( "name" ).asString(), is( "John Johnson" ) );
}
```
The test passed without a problem. So I do not think there is any problem for the this driver to use full text search procedures.

Maybe double check that the driver is connecting to a server that does have the full text index created. If you use "bolt+routing", then you might end up with any member in a cluster.

**Comment by zhenlineo** [comment]
Hi @deflorilemarului 
Any updates to this issue? We failed to reproduce the described problem. Could you give us some code to reproduce?

**Comment by zhenlineo** [comment]
Closing this issue due to missing information to continue.
@deflorilemarului Pls feel free to reopen this issue if you have more information to help us to continue.
