### ISSUE TITLE
How to use driver properly?

### ISSUE THREAD

**Issue by crazyyanchao** [neo4j/neo4j-java-driver#614]
What is the problem with too many drivers opened by the client?Can you describe the problem to be solved or how to optimize it?

**Comment by zhenlineo** [comment]
Hi @crazyyanchao,

The driver shaded netty inside. For each driver instance you created, an event loop group and a connection pool will be created. In other words, no threads nor connections could be shared/reused among different driver instances. So unless some constraints in your application environment that you cannot access to a global driver, we do not recommend creating more than one drivers.

I am closing this issue as questions about how to use the driver shall be asked in [Neo4j Online Community](https://community.neo4j.com/) instead.

Cheers,
Zhen
