### ISSUE TITLE
[Feature Request] Provide a way to specify the useragent or at least a prefix

### ISSUE THREAD

**Issue by jsoref** [neo4j/neo4j-java-driver#682]
- Neo4j version: 3.5/4.0
- Driver version: master (and older)

[newInstance](https://github.com/neo4j/neo4j-java-driver/blob/ad3ebc69bc7e8859bdf78f4048df3858605f5d47/driver/src/main/java/org/neo4j/driver/internal/DriverFactory.java#L78) calls [createConnectionPool](https://github.com/neo4j/neo4j-java-driver/blob/ad3ebc69bc7e8859bdf78f4048df3858605f5d47/driver/src/main/java/org/neo4j/driver/internal/DriverFactory.java#L119) which calls `ConnectionSettings(...)` with no way to influence it.

There is a [ConnectionSettings( AuthToken authToken, String userAgent, int connectTimeoutMillis )](https://github.com/neo4j/neo4j-java-driver/blob/ad3ebc69bc7e8859bdf78f4048df3858605f5d47/driver/src/main/java/org/neo4j/driver/internal/ConnectionSettings.java#L57), but it isn't called.
And the useragent is [final](https://github.com/neo4j/neo4j-java-driver/blob/ad3ebc69bc7e8859bdf78f4048df3858605f5d47/driver/src/main/java/org/neo4j/driver/internal/ConnectionSettings.java#L54)
- Expected behavior
- Actual behavior

### Steps to reproduce
1. Start Neo4j
2. Start some connections to the database
3. Connect to the database using [cypher-shell](https://github.com/neo4j/cypher-shell)
4. run:

```
CALL dbms.listConnections() YIELD connectionId, connectTime, connector, username, userAgent, clientAddress;
```

### Actual behavior
Note that all the useragents are `neo4j-java/1.7.5...` or `neo4j-java/dev`.

### Expected behavior
Ideally, the useragent might be `neo4j-java/dev cypher-shell/{version}` or similar for the cyphershell connection, and the other ones should be able to identify themselves beyond "hi, I'm a driver".

Once an API is available in the driver, the clients (e.g. cypher-shell) can be updated to use it...

**Comment by zhenlineo** [comment]
Hi @jsoref,

We recommend you to use username, clientAddress, and transaction meta data for identifying where a transaction is started.
You can read more about how to set tx meta data in this [article](https://medium.com/neo4j/new-features-in-1-7-neo4j-drivers-4bde893b1374).

**Comment by jsoref** [comment]
Yeah, that's really not terribly helpful. I'd much rather be able to use the useragent field in a useful manner. It's an advertised feature.

**Comment by zhenlineo** [comment]
Hi @jsoref,
For most use cases, a driver creates hundreds of connections with a neo4j server. Give a driver different useragent name will not help to find a specific tx when listing transactions. If your problem is specific to add a name for connections created by cypher shell, be free to create an issue there to suggest them to make use of tx metadata. Or you could also choose to create a specific user `cypher-shell` rather than `neo4j` when you login cypher shell.

Finally `useragent` is not part of driver's public API, I am not sure what do you mean by an `advertised feature`?

**Comment by jsoref** [comment]
[12.5.1. List all network connections](https://neo4j.com/docs/operations-manual/current/monitoring/connection-management/index.html#connection-management-list-connections)

> An administrator is able to view all network connections within the database instance. Alternatively, the current user may view all of their own network connections.

Name | Type | Description
-- | -- | --
userAgent | String | Name of the software that is connected. This information is extracted from the User-Agent request header for HTTP and HTTPS connections. It is available natively for Bolt connections which supply the agent string in an initialization message.

**Comment by jsoref** [comment]
FWIW, there are a number of different versions of cypher-shell each w/ their own quirks. It would have been immensely helpful to know which version of cypher-shell was performing actions. (Especially "does this client support Transactions properly?")

**Comment by zhenlineo** [comment]
Could you explain more about what feature it is actually missing? Do feel cypher-shell is missing a easy way to tell the cypher-shell version? or do you want to use driver useragent field? What is the goal that we would like to achieve?

**Comment by jsoref** [comment]
I want to be able to distinguish different cyphershell versions as an admin by looking at connections. That isn't about looking at "which user" or "let's create thirty different identical users who just differ by cyphershell version" (that should be clearly insane).

The same applies for non-cyphershell clients, if we have 3 client versions (just like 3 cyphershell versions), I should be able to see which version of a client is connecting and making requests (possibly harmful/broken ones).

In general, the way one distinguishes different (potentially flaky) clients that speak HTTP has been through the use of the user-agent field, and as noted, it's offered clearly in the documentation as a thing.

We deploy our software continuously and multiple versions will be running concurrently. The client-address is fairly useless as it generally runs in a kubernetes cluster where IP addresses come and go (and the version will change over time).

Sure, I could force each transaction to carry "this is my useragent version", but that's a really silly approach for something that isn't going to change for the life of a useragent, that's really the whole point of a useragent field. (And it definitely isn't practical for cyphershell.)

And beyond that, the transaction metadata field isn't exposed for connection lists, because it isn't a thing for connections, it's only for transactions (which usually aren't so long running that one would see them, although, I suppose on rare occasions a couple might show up).

In a simple case, we have 26 connections (from 20 clients) open to our database, one is my cyphershell (although at times there could be a couple more), the only open transaction when I look is my cyphershell looking for open transactions -- which means there's nothing I can look for to see anything about transaction metadata -- it doesn't exist.

All of the other clients are the exact same java driver version, which means there isn't anything distinguishable about the connections if I'm wearing a DBA hat. Sure, I could go ask each client instance "what are you", but a DBA should be able to see stuff by asking the DB questions.

---
If you didn't think the useragent was a useful thing, then I don't see why your driver would include a version at all (and it clearly does) -- which means someone in the neo4j driver development side decided it was worth reporting this information.

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Extended user-agent to be modifiable across all drivers](https://trello.com/c/v5RE99ya/492-extended-user-agent-to-be-modifiable-across-all-drivers)

**Comment by technige** [comment]
Hi @jsoref 

The user-agent metadata is currently intended only for internal and informal use by the driver. As @zhenlineo mentions, this is not something we have ever surfaced for use by higher-level software or applications. It's primary intended purpose is diagnostics.

I agree that the documentation in 12.5.1 is ambiguous, and this should make it clear that it is the driver version being reported, instead of simply saying "the software." We will look to get that corrected.

In terms of introducing a way for higher-level software to be able to modify or extend the user agent, I have added the item to our roadmap for future discussion, so this may appear in a future release, depending on the outcome of that discussion.

**Comment by martin-neotech** [comment]
@jsoref https://neo4j.com/docs/api/java-driver/4.1/org/neo4j/driver/Config.ConfigBuilder.html#withUserAgent-java.lang.String-

**Comment by martin-neotech** [comment]
This was added in 4.1 see https://github.com/neo4j/neo4j-java-driver/wiki/4.1-changelog
