### ISSUE TITLE
[Feature Request] Provide a way to fetch the next N records

### ISSUE THREAD

**Issue by elR1co** [neo4j/neo4j-java-driver#688]
Similar to `CompletionStage<Record> nextAsync()` method in ResultCursor, I would like a way to retrieve the next N records. Would it make sense to have a method `CompletionStage<List<Record>> nextAsync(int N`) in ResultCursor ?
Thanks a lot for the great work done.

**Comment by zhenlineo** [comment]
Hi @elR1co,

If you would like to specify the pulling size of each batch, you can configure `Config#fetchSize` and/or `SessionConfig#fetchSize` to specify how much records that you would like to pull in each batch. However you cannot define when to pull with our async API. The pulling time is decided automatically by the consuming speed of records. You can read more of the details in our [doc](https://neo4j.com/docs/migration-guide/4.0/upgrade-driver/#_back_pressure)

**Comment by elR1co** [comment]
Hi @zhenlineo 

Actually, I think I was missing something. I am currently working with driver 4.0.0 and Neo4j 3.5. So, I guess the fetchSize parameter has no impact. But, I used to think the nextAsync method was fetching only one record at a time from Neo4j server, so it would create too many roundtrips. Apparently, for Neo4j 3.5, you are already retrieving records by batches with default values between 300 and 1000, am I right (seen in LegacyPullAllResponseHandler)  ? And with Neo4j 4.0, this will be possible to configure that with fetchSize parameter. Is my understanding correct ?

**Comment by zhenlineo** [comment]
Hi @elR1co,

If you use 4.0 driver with 3.5 Neo4j, you will always pull all records in one batch regardless of your batch size. The limits 300 and 1000 you pointed out is used to enable/disable read from network buffer. When read is disabled, TCP will drop packages when there is too much data sent from server.

With Neo4j 4.0, you can config fetchSize and pull records in batches.

**Comment by elR1co** [comment]
@zhenlineo 

Thanks, I gonna close the issue. One last question : in my store procedure, I am doing a `stream().collect(Collectors.groupingBy(node -> counter.getAndIncrement() / chunkSize))` on my results to group several results into one big ones, in order to reduce the number of records sent. Would you recommend that ?
