### ISSUE TITLE
[Feature Request] Logger to debug cypher queries

### ISSUE THREAD

**Issue by elR1co** [neo4j/neo4j-java-driver#694]
I don't know if there is yet a way to handle that, but it would be cool to have, like Hibernate for example with org.hibernate.SQL, a specific logger to enable when we want to log all cypher queries + parameters.

By advance, I apologize if there is already something documented to achieve that.

Thanks a lot for the work done.

**Comment by zhenlineo** [comment]
Hi @elR1co,

We've already have this feature with this driver. Have a look at this [example of using slf4j](https://github.com/neo4j/neo4j-java-driver/blob/4.0/examples/src/main/java/org/neo4j/docs/driver/Slf4jLoggingExample.java). More logging options can be found in [Logging class](https://github.com/neo4j/neo4j-java-driver/blob/4.0/driver/src/main/java/org/neo4j/driver/Logging.java).
To log all cypher queries with parameters, you shall have `FINE` level enabled.

**Comment by elR1co** [comment]
If I am using slf4j, I guess the level to use should be `DEBUG` instead, right ?
And what should be the logger name ? I have tried the following, it works but I wanted to know if there was a better way :

```
<logger name="OutboundMessageHandler" level="debug" additivity="false">
       <AppenderRef ref="NEO4J"/>
</logger>
```
