### ISSUE TITLE
[Feature Request] Obtaining neo4j home path through Java API

### ISSUE THREAD

**Issue by francescoalongi** [neo4j/neo4j-java-driver#697]
- Driver version: 4.0.1

It would be great to have an API able to return the actual absolute path of the Neo4j home path, for instance it could return a String equal to `<path-to-neo4j-home>\database-XXX-XXX-XXX\installation-x.y.z`

**Expected behavior**
```
org.neo4j.driver.Driver driver = org.neo4j.driver.GraphDatabase.driver(url, AuthTokens.basic(username,password);
String absNeo4jPath = driver.getNeo4jHomePath();
```
So the content of the `absNeo4jPath` could be for instance, on Windows, `C:\neo4jDatabases\database-535b6c87-fc62-4a5e-9e82-502484e5185a\installation-4.0.1`

**Comment by zhenlineo** [comment]
Hi @francescoalongi,

Thanks very much for suggesting this feature to us. However the driver dose not and probably should not know the path to the Neo4j home path. As the driver connects to Neo4j via sockets, it does not know where the Neo4j installation is, whether locally or remotely.

Thanks again.
Zhen
