### ISSUE TITLE
Breaking change from 1.x -> 4.x not documented

### ISSUE THREAD

**Issue by jameskleeh** [neo4j/neo4j-java-driver#719]
The experimental `typeSystem()` method on `StatementRunner` was removed:

https://github.com/neo4j/neo4j-java-driver/blob/1.7/driver/src/main/java/org/neo4j/driver/v1/StatementRunner.java#L313

Even if it was experimental, it should be listed in the breaking changes.

Also - can you tell me how to migrate this code to the newer driver?

**Comment by jameskleeh** [comment]
Did some digging and found https://github.com/neo4j/neo4j-java-driver/commit/3b74944d4104248742e01839ab1b23dc9021b04e#diff-76c4d72a1036a3ab59dae44fe9afe7d7, so I know how to migrate

**Comment by michael-simons** [comment]
Thanks for the remark, you're right.

The `TypeSystem` has been moved from the internal package structure into a (still experimental) but stable API on the the `Driver` now, see https://github.com/neo4j/neo4j-java-driver/blob/4.0/driver/src/main/java/org/neo4j/driver/Driver.java#L173. 

This API is there to stay, we use it in a couple of downstream projects ourselves.

**Comment by gjmwoods** [comment]
The breaking changes section in the migration guide has been updated: https://neo4j.com/docs/migration-guide/4.0/upgrade-driver/#upgrade-driver-breakingchanges. Thanks for raising the issue @jameskleeh.
