### ISSUE TITLE
[Feature Request] BigInteger and BigDecimal values support

### ISSUE THREAD

**Issue by nryanov** [neo4j/neo4j-java-driver#727]
Hello!

Currently, as i see, neo4j-driver does no have (or i've missed it) direct support for BigInteger and BigDecimal values. 
If it is needed to store/retrieve them then it can be done using string, something like:
```
BigInteger value = ...
Value neo4jValue = Values.value(value.toString());
....
Record record = ...
BigInteger storedValue = BigInteger(record.get(0).asString());
```

Maybe there are other options, but i think that it would be nice to have helper methods which wrap these common steps.

**Comment by technige** [comment]
Hi @nryanov. Thank you for your suggestion.

Casting to and from types not directly related to the Cypher type system is not considered the role of the driver. This code should definitely sit in your application, so we won't be adding these kinds of extras.
