### ISSUE TITLE
Pass custom RetryLogic during session or driver creation

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j-java-driver#796]
Following the documentation ( https://neo4j.com/docs/driver-manual/current/session-api/configuration/#driver-async-transaction-fn ) for Transaction Functions, it states that the `retry logic` can be configured during session creation.

However, there doesn't seem to be away to pass any custom retry logic with a defined backoff strategy during session nor driver creation.

**Driver version**: Java driver 4.2.0

**Comment by gjmwoods** [comment]
Hi @ikwattro. That is an error in the documentation and custom retry logic cannot currently be configured in the drivers.
