### ISSUE TITLE
Neo4j Java driver 4.2.0 - support for two way TLS

### ISSUE THREAD

**Issue by faiz-usmani** [neo4j/neo4j-java-driver#801]
I am exploring the security options of Neo4j: accessing the DB using the Java (bolt) driver, v 4.2.0. 
The aim is to establish if mutual TLS is possible using the bolt based Java driver to connect to the database. 
For the purpose of experimentation I am using v 3.6.2 of the ONgDB. 

The DB instance is configured to allow only secure connections over 'bolt', however I cannot find the means within the driver API to supply the client certificate and key. Does this mean that even the driver version 4.2.0,  not allow two way TLS and essentially the security boils down to username-password over (one-way) TLS. This essentially means that client certificate auth cannot be configured as 'REQUIRED' for 'bolt'. 

Any advice will be much appreciated.

**Comment by michael-simons** [comment]
We don't support ONgDB. Please speak to them.

**Comment by faiz-usmani** [comment]
Thanks for your response Michael. 
All I need to understand is if the Java Neo4j Driver has the capability to use a client keystore (client private key and certificate), that can be used when client-auth is turned on (and set to 'required') on the Neo4j server. 
I do not think this has anything to do with Neo4j (or ONgDB): It would be down to whether the driver can use a client keystore. Could you please provide me information on that, or if that is something on the product road map.

**Comment by michael-simons** [comment]
Thanks for your understanding.

You can use a custom keystore in the Java driver. This is needed when you run your server with a custom, self signed certificate and you turned encrypted communication on.
The driver will check the servers certificate expiration date, the CA and also the hostname.

The keystore is not used for client auth.

`client_auth` is a server property and is mainly used for server to server communication (For cluster and backup purposes). 

Does that help?
