### ISSUE TITLE
Spring Command Line application doesn't terminate after Neo4j query (threads)

### ISSUE THREAD

**Issue by watery** [neo4j/neo4j-java-driver#877]
Hello, I came here after [StackOverflow](https://stackoverflow.com/q/67070372) and the [Community](https://community.neo4j.com/t/spring-command-line-application-doesnt-terminate-after-neo4j-query/36796).

I have a Spring Boot command line application — one that implements `CommandLineRunner` — that is already connecting to a PostgreSQL database with the Hikari driver with no issues. I added the Neo4j driver and now I'm experiencing that the application doesn't terminate after the `main()` method ends, if any query is issued to the database.

**Neo4j Version:** 4.2.5 Community  
**Neo4j Mode**: Single instance  
**Driver version**: Java driver 4.2.4.0
**Operating System:** Windows 10

### Steps to reproduce

You can find sources in the above linked Community thread.

There's a variable named `runQuery` that you can turn `true` or `false` to make the code run a query to the database or do nothing beside setting up the driver.

### Expected behavior

The application terminates after the `main()` method finishes.

### Actual behavior

If no query is sent to the database, the application behaves as expected. But if any query is sent (no matter if the result is consumed or not), the application stays active, no matter for how long I wait; moreover, inspecting it with VisualVM I can see that the `main()` thread has really terminated, but other `Neo4jDriverIO` threads are still active.

I have to add that if I explicitly terminate the program (i.e. by hitting the stop button in the IDE), no error appears and the program seems to terminate gracefully, it looks just like the driver isn't signaled to close itself after `main()` completed, but sits waiting.

In fact, if I invoke `driver.close()` at the end of the `main()` method, the application terminates.

**Comment by fbiville** [comment]
Thanks @watery, I just replied to your question on https://community.neo4j.com/t/spring-command-line-application-doesnt-terminate-after-neo4j-query/36796. This is a usage issue and you actually found the solution: close the driver before the application exits. Let's continue the conversation in https://community.neo4j.com/ if you have further questions.
